### PR TITLE
[test] Extract adapter for QString matching

### PR DESCRIPTION
**Pull request by ricab**

### CODE REVIEW

**Comment by ricab** [comment]
Need this again in hyper-v tests.

**Review by Saviq — APPROVED** [review]
Yups.

bors merge

**Comment by Saviq** [comment]
bors retry

**Comment by ricab** [comment]
bors r=Saviq

**Comment by Saviq** [comment]
bors retry

**Comment by Saviq** [comment]
Will you work now?

bors retry

**Comment by ricab** [comment]
bors r=Saviq

**Pull request merged**
