### PR TITLE
[daemon] Fix file and http based launching regression

### PR DESCRIPTION
**Pull request by townsend2010**
Due to 91fe3c34561.

### CODE REVIEW

**Review by luis4a0 — APPROVED** [review]
Yeah!

**Comment by luis4a0** [comment]
bors retry

**Comment by luis4a0** [comment]
bors retry

**Comment by ricab** [comment]
This is failing integration tests because of the inability to read mount setting: https://github.com/canonical/multipass/runs/2989810835#step:4:1141 

Merging manually.

**Comment by luis4a0** [comment]
Thanks @ricab!

**Pull request merged**
