### PR TITLE
[snapshots] Unit tests

### PR DESCRIPTION
**Pull request by ricab**

### CODE REVIEW

**Comment by ricab** [comment]
Can't change base branch to fix-snapshot-restore-rollback ATTOW, but no merge until rebased on main!

**Comment by ricab** [comment]
Oh, GH doesn't let me reopen :thinking:

**Comment by townsend2010** [comment]
Hey @ricab!

In order to be able to reopen this PR, the `snapshots-unit-tests` branch SHA needs to match what this PR thinks is the last commit, so in this case, the SHA would be `f6bfb48`.

**Comment by ricab** [comment]
Hmm I see, thanks! Well I have since moved on from that so I guess I'll live with the replacement.

**Pull request closed without merging**
