### PR TITLE
[git] move xz-embedded to canonical org

### PR DESCRIPTION
**Pull request by Saviq**

### CODE REVIEW

**Comment by luis4a0** [comment]
Altough I was able to update the submodules locally, Travis gives an error about authentication:
Cloning into '/home/travis/build/canonical/multipass/3rd-party/grpc'...
remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/canonical/grpc.git/'
fatal: clone of 'https://github.com/canonical/grpc.git' into submodule path '/home/travis/build/canonical/multipass/3rd-party/grpc' failed
Failed to clone '3rd-party/grpc'. Retry scheduled

Should Travis be granted some permission to access those repos in `github.com/canonical/`?

**Comment by luis4a0** [comment]
Actually, it worked for mac... was the access granted in the meantime?

**Comment by luis4a0** [comment]
There still exist access errors, see [here](https://travis-ci.org/github/canonical/multipass/jobs/675358517#L209).

The issue seems to be now only with the xz-embedded repo. Locally, I was not able to clone the repo using https, but I could do it indeed using ssh. Maybe changing the address solves the issue.

**Comment by Saviq** [comment]
It was a temporary issue after all…

**Pull request closed without merging**
