### PR TITLE
[build] Use OpenSSL instead of gRPC's boringssl

### LINKED ISSUE #1368: [snap] use Ubuntu's OpenSSL packages
Rather than building and bundling BoringSSL, the snap could use the packages available from the Ubuntu archive.

This would, at least, get us a better security story and ability to build on all arches Ubuntu support (BoringSSL doesn't support big-endian at the moment).

### PR DESCRIPTION
**Pull request by townsend2010**
Fixes #1368

### CODE REVIEW

**Comment by Saviq** [comment]
You can remove the `architectures` clause from `snapcraft.yaml`:

https://code.launchpad.net/~saviq/+snap/multipass-all
image

**Comment by townsend2010** [comment]
> You can remove the `architectures` clause from `snapcraft.yaml`:

Ah, right, cool!

**Comment by Saviq** [comment]
Noice!

bors merge

**Comment by Saviq** [comment]
Hum. Try again?

bors merge

**Pull request merged**
