### PR TITLE
update flutter to 3.24.1 and our deps

### PR DESCRIPTION
**Pull request by andrei-toterman**

### CODE REVIEW

**Comment by andrei-toterman** [comment]
Welp, this can't be right...
image
image
It only happens in the snap, not if I run the locally built GUI.
Also, the app flickers regularly...

**Comment by ricab** [comment]
Is that an April's fools build?

**Comment by ricab** [comment]
I gotta say, it still looks pretty good :dark_sunglasses:

**Comment by andrei-toterman** [comment]
Seems to be a case of the good old RGB/BGR confusion. If I swap those color channels in the screenshot, it all looks good. I shall report it.

**Review by levkropp — APPROVED** [review]
Looks good to me. Builds, passes tests and GUI looks correct on Ubuntu 24.04 + KDE

**Comment by ricab** [comment]
Hey @andrei-toterman , the release packages are getting signed, so I think we can go ahead with this. Could you please resolve the new conflicts?

**Comment by andrei-toterman** [comment]
Superseded by #3713

**Pull request closed without merging**
