### PR TITLE
Release 1.3.0

### PR DESCRIPTION
**Pull request by Saviq**

### CODE REVIEW

**Comment by ricab** [comment]
Missing #1568 ?

**Comment by luis4a0** [comment]
Succesfully tested on Windows:
-upgrade from a previous version
-hyper-v and virtualbox backends
-launch, start, suspend, mount, stop, delete, purge commands
-windows terminal integration
-gui functionalities
-all images and appliances in `multipass find`

**Comment by ricab** [comment]
I did some smoke testing of [multipass-1.3.0-rc.220+g3d3924ad.mac-Darwin.pkg](https://multipass-ci.s3.amazonaws.com/multipass-1.3.0-rc.220%2Bg3d3924ad.mac-Darwin.pkg) on macOS, both hyperkit and virtualbox, loosely following our recipe, plus some additional exercising (e.g. trying different images). I also tried launching one of the new appliance images. Everything looked ok to me, except:

- old notices shown in the installer
- appliance image was faulty on Friday and was not automatically updated today. It worked today when I manually cleaned it to force a re-download.

**Comment by Saviq** [comment]
On Linux:
- `multipass shell`
- `multipass stop primary`
- `multipass launch core18`
- `snap refresh multipass --candidate`
- `snap connections multipass` looks good
- `multipass list`
- `multipass shell`
- `multipass exec primary -- ls Home`
- `multipass delete primary`
- `multipass restore primary`
- `multipass delete --purge --all`
- `for app in adguard-home mosquitto nextcloud openhab plexmediaserver; do multipass launch appliance:$app || break; done`
- `multipass shell`
- `multipass suspend primary` (Found a prior bug: #1581)
- `multipass shell`
- `multipass exec primary -- ls Home`
- `multipass launch snapcraft:core20`
- `multipass delete --purge --all`
- `snap connect multipass:lxd lxd`
- `sudo multipass set local.driver=lxd`
- `multipass shell`
- `multipass exec primary -- ls Home`
- `multipass delete --purge --all`

**Comment by Saviq** [comment]
bors merge a=Saviq r=ricab,luis4a0,Saviq

**Pull request merged**
