### PR TITLE
Fix `restart` not showing new version

### PR DESCRIPTION
**Pull request by Sploder12**
Partial fix for #3672, unable to reproduce `start` behavior. 

When running `restart` with a new version of Multipass available, no notification would be shown but the field is present in the gRPC reply.

This PR makes it so the daemon properly populates that field for `restart` and has the CLI respond to it.

### CODE REVIEW

**Review by sharder996 — APPROVED** [review]
This looks good to me as is and as such I'm going to approve. 

However, I think some of the logic can be improved. 
- `write_reply` is unnecessary since writing an empty reply is idempotent
- The `config->update_prompt->is_time_to_show()` check and `config->update_prompt->populate()` can be simplified with a single call to `populate_if_time_to_show()`. `populate()` displays the new version info every time the command is called, which is probably a bit too spammy. `populate_if_time_to_show()` will only display new version info every `notify_user_frequency` which is inline with what the other commands do.

**Comment by ricab** [comment]
Hmm, I would rather avoid being too naggy. @Sploder12 WDYT?

**Comment by Sploder12** [comment]
> Hmm, I would rather avoid being too naggy. @Sploder12 WDYT?

I agree, I'd want to avoid that too @ricab.

**Comment by ricab** [comment]
Alright, let's wait for it then, thanks.

**Review by sharder996 — APPROVED** [review]
LGTM! Will wait for CI before merging.

BTW, if you use one of these [keywords](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/using-keywords-in-issues-and-pull-requests#linking-a-pull-request-to-an-issue) along with the issue number, the issue will be closed automatically when the PR gets merged.

**Comment by sharder996** [comment]
Fixes #3672

**Pull request merged**
