### PR TITLE
[tests] Fix MemorySize tests depending on locale

### PR DESCRIPTION
**Pull request by ricab**
Avoids unsupported number representations, e.g. with a comma separating integers and decimal parts.

### CODE REVIEW

**Review by sharder996 — COMMENTED** [review]
Hey @ricab, this looks fine, but just curious; couldn't one have just replaced `std::to_string()` with `fmt::format()` everywhere and eliminated the need for the template? It's not providing any value outside the file and it's a just simple wrapper.

**Comment by ricab** [comment]
Hi @sharder996. We could, but we'd have to specify the format each time, which would make it a little harder for the reader inline. Contrast the two:

```cpp
EXPECT_EQ(mp::MemorySize{fmt::format("{}", val) + "M"}.in_kilobytes(), val * kilo);
EXPECT_EQ(mp::MemorySize{to_str(val) + "M"}.in_kilobytes(), val * kilo);
```

The second form follows DRY in that it avoids repeating the (empty) format everywhere, and it's just a little bit easier to read: `to_str` has a lighter syntax and immediately makes the intent clear.

**Comment by ricab** [comment]
I don't know, I tend to think that adding support for locales would have to be a holistic task, where we visited every input/output...

**Comment by sharder996** [comment]
Adding support for different locales isn't an issue right now and it doesn't block this.

bors r+

**Pull request merged**
