### PR TITLE
[client/cli] Rename register command to authenticate

### PR DESCRIPTION
**Pull request by townsend2010**
Also has an "auth" alias to shorten the typing

### CODE REVIEW

**Review by Saviq — CHANGES_REQUESTED** [review]
Please rename `registered-certs` / `registered_certs_dir`, too.

**Comment by townsend2010** [comment]
> Please rename `registered-certs` / `registered_certs_dir`, too.

Done.

**Review by Saviq — APPROVED** [review]
Thanks!

bors merge

**Comment by Saviq** [comment]
bors retry

**Comment by Saviq** [comment]
bors retry

**Comment by Saviq** [comment]
One of those times.

bors merge

**Pull request merged**
