### PR TITLE
[sftp] Fix streaming of null-containing data

### LINKED ISSUE #2005: transfer using '-' breaks with binary data
**Describe the bug**

Text files work fine with transfer using  '-'.  Binary files do not for stdout.

**To Reproduce**

case 1: text file
```
chris@hp:~/git/craft-providers$ echo -e "test me" > foo.txt
chris@hp:~/git/craft-providers$ multipass transfer foo.txt itest-TAFYIJFR:/tmp/foo.txt 
chris@hp:~/git/craft-providers$ multipass exec itest-TAFYIJFR cat /tmp/foo.txt | od -t x1
0000000 74 65 73 74 20 6d 65 0a
chris@hp:~/git/craft-providers$ multipass transfer itest-TAFYIJFR:/tmp/foo.txt - | od -t x1
0000000 74 65 73 74 20 6d 65 0a
```

case 2: binary file with nulls
```
chris@hp:~/git/craft-providers$ echo -e "\x00\x00test me" > foo.bin
chris@hp:~/git/craft-providers$ multipass transfer foo.bin itest-TAFYIJFR:/tmp/foo.bin 
chris@hp:~/git/craft-providers$ multipass exec itest-TAFYIJFR cat /tmp/foo.bin | od -t x1
0000000 00 00 74 65 73 74 20 6d 65 0a
chris@hp:~/git/craft-providers$ multipass transfer itest-TAFYIJFR:/tmp/foo.bin - | od -t x1
0000000
```

I do believe using '-' for transferring input works fine.

**Expected behavior**

Transfer to work for binary files.

**Additional info**
 - OS:  Ubuntu
- `multipass version` 1.6.2

### PR DESCRIPTION
**Pull request by ricab**
Fixes #2005.

### CODE REVIEW

**Review by townsend2010 — APPROVED** [review]
LGTM, thanks.  I restarted the CI run since the Snap Store is now fixed.  Will wait for that before merging.

**Comment by ricab** [comment]
Thanks @townsend2010, I meant to have a go at a test for this but didn't get to it. Let me see if I can hack up something quick.

**Comment by townsend2010** [comment]
Hey @ricab, ok, great, thanks!

**Comment by ricab** [comment]
Done. It took me a bit to get that reading mock right.

**Review by townsend2010 — CHANGES_REQUESTED** [review]
Boo, the Windows build is failing:
```
Error: D:\a\multipass-private\multipass-private\tests\test_sftp_client.cpp(262): error C3487: 'unsigned __int64': all return expressions must deduce to the same type: previously it was 'unsigned long'
```

**Comment by ricab** [comment]
Ahh right, let me fix that.

**Comment by ricab** [comment]
Fixed, thanks for pointing it out.

**Review by townsend2010 — APPROVED** [review]
Great, thanks, all good.

bors merge

**Comment by townsend2010** [comment]
Again...

bors merge

**Comment by Saviq** [comment]
bors retry

**Pull request merged**
