### PR TITLE
[daemon] Make sure there is a path before checking if it exists

### LINKED ISSUE #2121: [regression] LXD instances are deleted on daemon startup
Due to 725713a81, all LXD instances are deleted on daemon start up.  This is due to LXD instances not having a path and as such, the `QFile::exists()` will always return `false` and the daemon will delete it.

### PR DESCRIPTION
**Pull request by townsend2010**
Fixes #2121

### CODE REVIEW

**Review by ricab — COMMENTED** [review]
Yep, thanks for the fix. Tests need adapting though...

**Comment by townsend2010** [comment]
Right, working on those now :smiley:

**Review by ricab — APPROVED** [review]
LGTM, thanks.

bors r+

**Comment by townsend2010** [comment]
Ugh, seems there is some fragility in the qemu integration test around discovery of snap being installed in the instance.

bors retry

**Comment by townsend2010** [comment]
Ugh, again, I had to cancel the Mac build due a test hanging.

bors retry

**Pull request merged**
