### PR TITLE
[LXD] Handle storage pools better

### PR DESCRIPTION
**Pull request by townsend2010**
This will use the default storage pool if it exists. Otherwise, it will use a multipass storage pool and create it if it doesn't exist.

### CODE REVIEW

**Comment by Saviq** [comment]
The `multipass` pool should be used if it exists, shouldn't it? I mean:

```
if pool("multipass"): return pool("multipass")
elif pool("default"): return pool("default")
else create_pool("multipass"): return pool("multipass")
```

**Comment by townsend2010** [comment]
> The `multipass` pool should be used if it exists, shouldn't it?

Hmm, I guess.  The advice was to use the `default` pool first, if it exists.  If it doesn't, then create/use a `multipass` pool.  But I suppose if there is already a `multipass` pool available, then at some point, there wasn't a `default` pool.  But I do see what you mean, if we did create a `multipass` pool and the user decided to create a `default` pool later, we should continue to use the `multipass` pool, so I'll fix that.

**Comment by Saviq** [comment]
> But I do see what you mean, if we did create a `multipass` pool and the user decided to create a `default` pool later, we should continue to use the `multipass` pool, so I'll fix that.

We're missing a test case for when both of the pools exist, don't we? And we lost the profile update test?

**Comment by townsend2010** [comment]
> We're missing a test case for when both of the pools exist, don't we?

Ok, right.

> And we lost the profile update test?

We no longer are updating the default profile with the PR, hence dropping the test for that.

**Comment by townsend2010** [comment]
> We're missing a test case for when both of the pools exist, don't we?

Done.

**Comment by Saviq** [comment]
> at some point, there wasn't a `default` pool.

That, or someone created the `multipass` pull manually.

I triggered CI to get new builds and will test soon.

**Review by Saviq — APPROVED** [review]
Works well!

I launched an instance with LXD not initialized, then another one in the `multipass` pool, then removed those and the pool, and launched one in the `default` pool after. And all that without restarting the daemon, so good!

**Comment by Saviq** [comment]
bors merge

**Comment by Saviq** [comment]
@townsend2010 this needs an update for clang-format-12 and some conflict resolution.

**Comment by townsend2010** [comment]
bors r=Saviq

**Pull request merged**
