### PR TITLE
[mocks] Add libssh premock test fixture

### PR DESCRIPTION
**Pull request by townsend2010**

### CODE REVIEW

**Review by luis4a0 — APPROVED** [review]
Thanks for this @townsend2010! The code looks great to me. There is one test failing in Windows. I'll bors this after realizing it.

**Comment by luis4a0** [comment]
bors try

**Comment by townsend2010** [comment]
Hey @luis4a0,

Thanks!  I figured out the test failure and just disabled the test on Windows since that code path is not used on Windows.

**Comment by luis4a0** [comment]
Great @townsend2010!

bors r+

**Pull request merged**
