### PR TITLE
utils: fix deprecated initalization of QFD::Permissions

### PR DESCRIPTION
**Pull request by Saviq**

### CODE REVIEW

**Review by townsend2010 — APPROVED** [review]
Cool, thanks!  I don't see those particular deprecation warnings any more.

bors merge

**Comment by townsend2010** [comment]
Grr, try again...

bors retry

**Comment by townsend2010** [comment]
Try again...

bors retry

**Comment by townsend2010** [comment]
bors retry

**Comment by townsend2010** [comment]
One more time...

bors retry

**Comment by townsend2010** [comment]
Ok, gonna try one last time, then I'm going to merge it manually.  I mean it `bors`, I'll merge it manually if you don't get your act together.  I'm warning you!!!!!

bors retry

**Comment by townsend2010** [comment]
Running bors to get the merge commit and will manually merge.

**Comment by townsend2010** [comment]
bors retry

**Comment by townsend2010** [comment]
bors cancel

**Comment by Saviq** [comment]
> Running bors to get the merge commit and will manually merge.

IMO that's excessive, it's easy enough to craft that commit yourself, and it doesn't then cheat that bors, indeed, merged it.

**Comment by townsend2010** [comment]
> IMO that's excessive, it's easy enough to craft that commit yourself, and it doesn't then cheat that bors, indeed, merged it.

Ok, that's fair.

> ...you can just push to ~`master`~`main`, bors will cancel itself.

When I did push to `main`, `bors` kept running until I explicitly told `bors` to cancel.  Perhaps it takes a while for the manually merge to be noticed?

> Note that *doesn't*, on its own, cancel the CI runs that trigger on a push to `staging`.

Right.  I went to the running Workflows and tried multiple times to cancel, but I don't think Github Actions honors the cancel all of the time.

**Comment by Saviq** [comment]
> When I did push to `main`, `bors` kept running until I explicitly told `bors` to cancel. Perhaps it takes a while for the manually merge to be noticed?

Hmm. Maybe. Or maybe it notices HEAD changes, but not base? (at least not until it fails to push).

> Right. I went to the running Workflows and tried multiple times to cancel, but I don't think Github Actions honors the cancel all of the time.

The problem is the `if: ` bit in steps. If it says `always()` (as it needs to, if you want it to run despite skipping previous a step), that step won't be cancelled… I tried to fix all the cases to have `always() && !cancelled()`, but may have missed some - and I'm not clear on whether that would mean it _does_ get cancelled…

**Comment by townsend2010** [comment]
You would think if someone wants to cancel a workflow run, they just want it to stop period (like `kill -9` the whole thing) and not care about subsequent steps :shrug:

**Comment by Saviq** [comment]
> You would think if someone wants to cancel a workflow run, they just want it to stop period (like `kill -9` the whole thing) and not care about subsequent steps shrug

Well, that allows you to do cleanup. Like in the Testflinger case, that gives me a chance to cancel running jobs

**Comment by Saviq** [comment]
But what is crazy, is the implicit `if: success()`, which only gets overridden if you have `always()` in your condition. Otherwise it just gets app`&&`ed…

**Pull request merged**
