### PR TITLE
Bridging lxd

### PR DESCRIPTION
**Pull request by ricab**
This implements `launch --network` with the LXD backend.

### CODE REVIEW

**Review by Saviq — APPROVED** [review]
Lookin' good!
```plain
$ multipass launch --network br0 --network br0
# …
  IPv4 address for enp5s0: 10.152.94.232
  IPv6 address for enp5s0: fd42:254b:731a:5118:5054:ff:fe02:4e46
  IPv4 address for enp6s0: 10.2.0.14
  IPv4 address for enp7s0: 10.2.0.34
```

**Comment by ricab** [comment]
Note to self: update docs.

**Comment by ricab** [comment]
Docs updated.

**Review by Saviq — APPROVED** [review]
Yupsies!

bors r+

**Pull request merged**
