### PR TITLE
[cosmetic] Reorder util functions into small lumps

### PR DESCRIPTION
**Pull request by ricab**
Hopefully easier to sift through this way.

### CODE REVIEW

**Comment by ricab** [comment]
@townsend2010 how about now?

**Comment by ricab** [comment]
Gahh we shouldn't have such differences outside of platform

**Comment by ricab** [comment]
@townsend2010 I aligned the utils with the other side: brought extra ones from there and also added a missing log message. They are not used here ATM but they could be, so I think this makes more sense than tying to any platform.

**Comment by townsend2010** [comment]
@ricab,

I totally agree that the utils shouldn't be platform/branch dependent, thanks for fixing that- it's been bugging me for some time now and just never did it myself :smiley:

**Comment by townsend2010** [comment]
bors merge

**Pull request merged**
