### PR TITLE
[ci] Remove macOS 10.15 from integration tests

### PR DESCRIPTION
**Pull request by townsend2010**
Apple has dropped support for this version and so has Multipass.

### CODE REVIEW

**Review by luis4a0 — APPROVED** [review]
Yeah, this is the right thing to do! Nice to see OCaml stuff going away :)

**Comment by townsend2010** [comment]
bors cancel

**Comment by townsend2010** [comment]
bors retry

**Comment by townsend2010** [comment]
Hello?

bors retry

**Comment by townsend2010** [comment]
bors r=luis4a0

**Pull request merged**
