### PR TITLE
[settings] Accept const ref in get helper

### PR DESCRIPTION
**Pull request by ricab**
Split into separate PR on review request.

### CODE REVIEW

**Comment by ricab** [comment]
@Saviq Hey, here is the separate PR for the const ref. I'll rebase the other PR on this.

**Comment by ricab** [comment]
Actually, since this was the first commit in the winterm branch, I could just make the branch point to it.

**Comment by Saviq** [comment]
@ricab should we have a test accompany this change?

**Comment by ricab** [comment]
@Saviq as before, testing this would require mocking `QSettings`. We have `MockSettings`, but that mocks our own `Settings` class to test other things in multipass (get and set cmds, etc.). Since `QSettings` is outside of our control, I'd need an additional level of indirection. If you want, I can try to do that now?

**Comment by Saviq** [comment]
No, it's fine. I actually thought of a compile-time check, but the actual code will do it instead…

bors r+

**Comment by Saviq** [comment]
Hmm?

bors r+

**Pull request merged**
