### PR TITLE
Start the VM if needed on `exec`

### LINKED ISSUE #2236: Issuing `exec` on a non-running instance should automatically start the instance
If I execute an alias on an instance and that instance is not running, I would expect the instance to be automatically started and then the alias executes.  A message should be printed out saying what is happening.

### PR DESCRIPTION
**Pull request by luis4a0**
Fixes #2236.

### CODE REVIEW

**Review by townsend2010 — CHANGES_REQUESTED** [review]
The output when starting the instance and then displaying `stdout` from the instance needs fixing.  For example:
```
$ multipass exec test-start-exec -- ls -la                      
Starting test-start-exec  total 28                                              
drwxr-xr-x 4 ubuntu ubuntu 4096 Nov  1 10:34 .
drwxr-xr-x 3 root   root   4096 Nov  1 10:34 ..
-rw-r--r-- 1 ubuntu ubuntu  220 Feb 25  2020 .bash_logout
-rw-r--r-- 1 ubuntu ubuntu 3771 Feb 25  2020 .bashrc
drwx------ 2 ubuntu ubuntu 4096 Nov  1 10:34 .cache
-rw-r--r-- 1 ubuntu ubuntu  807 Feb 25  2020 .profile
drwx------ 2 ubuntu ubuntu 4096 Nov  1 10:34 .ssh
```
You see the `Starting test-start-exec  ` in the first line of output and that should not be there.

**Comment by townsend2010** [comment]
Hey @luis4a0,

> Do you mean the sentence `Starting test-start-exec` must be erased, or just add a new line at its end?

Well, I think it should disappear when the instance finishes starting.  That said, I see when `shell` starts a stopped instance, the same thing happens.  It's just more apparent in this PR due to the expected output not being correct.

**Comment by luis4a0** [comment]
Done!

**Review by townsend2010 — CHANGES_REQUESTED** [review]
Hey @luis4a0,

Although this works fine, I'm not very fond of the approach.  I did a little digging and found that there is a bug in `AnimatedSpinner`.  Here is a diff that should fix this (along with the `shell` issue I referenced earlier):
```diff
diff --git a/src/client/cli/cmd/animated_spinner.cpp b/src/client/cli/cmd/animated_spinner.cpp
index 8672042f..88f868ae 100644
--- a/src/client/cli/cmd/animated_spinner.cpp
+++ b/src/client/cli/cmd/animated_spinner.cpp
@@ -26,7 +26,7 @@ namespace
 void clear_line(std::ostream& out)
 {
     out << "\r" << std::setw(80) << " ";
-    out << "\r";
+    out << "\r" << std::flush;
 }
 }
 
diff --git a/src/client/cli/cmd/exec.cpp b/src/client/cli/cmd/exec.cpp
index 06a22966..6cca240f 100644
--- a/src/client/cli/cmd/exec.cpp
+++ b/src/client/cli/cmd/exec.cpp
@@ -50,11 +50,7 @@ mp::ReturnCode cmd::Exec::run(mp::ArgParser* parser)
     request.set_verbosity_level(parser->verbosityLevel());
     ReturnCode return_code;
     while ((return_code = dispatch(&RpcMethod::ssh_info, request, on_success, on_failure)) == ReturnCode::Retry)
-    {
-        // ReturnCode::Retry will be returned only when the VM had to be started. If this happened, it is necessary
-        // to remove the line which contained the text "Starting..." and the spinner.
-        cerr << "\b";
-    }
+        ;
 
     return return_code;
 }
```

**Comment by luis4a0** [comment]
Excellent, thanks! Flushing worked like a charm.

**Review by townsend2010 — APPROVED** [review]
LGTM, thanks!

bors merge

**Comment by Saviq** [comment]
Not happy.

bors retry

**Comment by townsend2010** [comment]
Grr, one last try....

bors retry

**Pull request merged**
