### PR TITLE
[ci] authenticate the root user before uninstalling on macOS

### PR DESCRIPTION
**Pull request by Saviq**

### CODE REVIEW

**Comment by Saviq** [comment]
bors try

**Comment by Saviq** [comment]
bors try

**Review by townsend2010 — APPROVED** [review]
Ok, LGTM

bors merge

**Comment by Saviq** [comment]
bors retry

**Comment by Saviq** [comment]
Doesn't seem to have worked very well :P

```plain
+ _run /usr/local/bin/multipass set local.passphrase=foobar
+ ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null cibot@192.168.219.220 -- /usr/local/bin/multipass set local.passphrase=foobar
Warning: Permanently added '192.168.219.220' (ECDSA) to the list of known hosts.
Unable to read/write settings: access error (consider running with an administrative role)
+ true
+ _run sudo /usr/local/bin/multipass register foobar
+ ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null cibot@192.168.219.220 -- sudo /usr/local/bin/multipass register foobar
Warning: Permanently added '192.168.219.220' (ECDSA) to the list of known hosts.
Error: Unknown command or alias 'register' (try "multipass help" or "multipass aliases")
```

**Comment by Saviq** [comment]
bors r=townsend2010

**Comment by townsend2010** [comment]
Try again...
bors retry

**Pull request merged**
