### PR TITLE
Move `--network` param parsing to client

### PR DESCRIPTION
**Pull request by ricab**
~~https://github.com/canonical/multipass/compare/control-network-interfaces...network-param-handling~~

### CODE REVIEW

**Comment by ricab** [comment]
Hey @luis4a0 I rebased the network-param branch on top of your latest stuff and changed the base of the PR accordingly. If you are ok with it we can merge here and have one less branch to merge on the other side. But let me know if you prefer some other way of handling it.

Note: I intend to pay the test debt in this branch later on (before merging into master I suppose).

**Comment by ricab** [comment]
BTW, [this fails](https://travis-ci.org/github/canonical/multipass/builds/728963328#L4539) because it is not picking up the control branch on the other side. If you want I can create a void network-param-handling on top of control-... there just so it picks up the remaining backend implementations.

**Comment by ricab** [comment]
Actually just did that and restarted the mac build. We can erase that branch once this is merged.

**Review by luis4a0 — APPROVED** [review]
Looks good

**Pull request merged**
