### PR TITLE
[url_downloader] Add HTTP UserAgent header info

### LINKED ISSUE #3049: Add Multipass-specific HTTP UserAgent header info
Add Multipass-specific HTTP UserAgent info when initiating a network connection.

### PR DESCRIPTION
**Pull request by townsend2010**
Fixes #3049

---

@nathan-j-hart This will be in the form of something like:
`Multipass/1.11.1 (macos-11.3; arm64)`

Let me know what you think.

### CODE REVIEW

**Comment by nathan-j-hart** [comment]
Those are the must-have data points, as long as it is consumable by graylog / influxDB (presumably we can parse this however we want) then it should be good.

**Comment by townsend2010** [comment]
I'm pretty sure graylog will just capture this as a string and then when we import it into influxDB, we'll have to parse things in the string how we see fit, but should be doable.

**Comment by townsend2010** [comment]
Ok, after rebooting the integration test machine, this passed: https://github.com/canonical/multipass/actions/runs/4859933146

**Pull request merged**
