### PR TITLE
[mounts] Fix mount handling when suspending

### LINKED ISSUE #2790: [regression] Suspend broken with qemu native mounts
`suspend` does not work properly when a new `native` mount is defined with the `qemu` driver (both on Linux and macOS).

A fix will be incoming soon.

### PR DESCRIPTION
**Pull request by townsend2010**
Fixes #2790

### CODE REVIEW

**Review by luis4a0 — APPROVED** [review]
Hey @townsend2010! Code looks neat and I tested it works. Thanks!

**Comment by townsend2010** [comment]
Try again...

bors retry

**Comment by luis4a0** [comment]
bors retry

**Comment by luis4a0** [comment]
Ouch, sorry, the page didn't update and I retried again :(

**Comment by luis4a0** [comment]
Oops, wrong button :(

**Comment by luis4a0** [comment]
bors retry

**Comment by luis4a0** [comment]
bors cancel

**Comment by luis4a0** [comment]
Ok, rebased from main. That should do.

bors r+

**Comment by townsend2010** [comment]
Seems to be unrelated issues in the Hyper-V integration tests.  Merging manually...

**Pull request merged**
