### PR TITLE
Generalize catch all

### PR DESCRIPTION
**Pull request by ricab**
Generalize catch-all wrapper, to handle other sorts of callables, with different return types.

### CODE REVIEW

**Comment by ricab** [comment]
bors try+

**Comment by townsend2010** [comment]
Seems there was some issue on the private side.  I'm going to mark this draft and then back to ready to kick off a clean run.

**Review by townsend2010 — APPROVED** [review]
Ok, this LGTM, thanks!

**Comment by townsend2010** [comment]
bors merge

**Pull request merged**
