### PR TITLE
Filter duplicate instances

### LINKED ISSUE #3055: Multipass crashes on repeated cli arguments
**Describe the bug**
Passing repeated arguments causes the daemon to crash on `multipass delete`

**To Reproduce**
1. `multipass launch foo`
2. `multipass delete foo foo`

**Expected behavior**
The instance will be deleted

### PR DESCRIPTION
**Pull request by sharder996**
Replaces #3056. That work becomes outdated if this is merged in.

Fixes #3055

### CODE REVIEW

**Review by ricab — APPROVED** [review]
LGTM, thank you! 

Just waiting for the base branch to be merged before merging this.

**Comment by ricab** [comment]
Alright, let's get this in.

bors r+

**Comment by ricab** [comment]
bors retry

**Comment by townsend2010** [comment]
bors retry

**Comment by ricab** [comment]
bors retry

**Comment by townsend2010** [comment]
Ok, I got integration tests to pass manually.  Will merge...

**Pull request merged**
