### PR TITLE
[gui] set version to 1.15.0

### PR DESCRIPTION
**Pull request by andrei-toterman**
GUI version must be updated manually, unfortunately...

### CODE REVIEW

**Comment by ricab** [comment]
Oh... We'll need RC2 then.

**Review by ricab — APPROVED** [review]
Hey @andrei-toterman, I am approving, but where does this show in the GUI? Also, how difficult would it be to make it pick up from the build, as the CLI and daemon do?

**Comment by andrei-toterman** [comment]
It is shown on macOS in the app info
image
As for making CMake fill that value in at configure time, it should be entirely possible, but not using CMake's configure_file, since that would introduce some difficulties. We'd have to use some custom regex stuff, but it shouldn't be too hard.

**Comment by ricab** [comment]
OK thanks, I opened #3803 for that.

**Pull request merged**
