### PR TITLE
[daemon] Refactor instance selection

### PR DESCRIPTION
**Pull request by ricab**
Refactor how we select instances given instance name args, as well as how we react when there is a problem with those args.

### CODE REVIEW

**Comment by ricab** [comment]
A follow up would be to extract a bunch of the stuff in the unnamed namespace of daemon.cpp into a separate unit.

**Comment by sharder996** [comment]
#3055 is still reproducible and will need to be addressed again

**Review by townsend2010 — COMMENTED** [review]
Hy @ricab!

This looks good to me.  I only have one question about something that was removed.

I see the `LaunchError` `ErrorCodes` `enum` was modified to not have an `INSTANCE_EXISTS` error code.  I'm just wondering how this is now communicated to the client that this error condition occurs when launching?

**Review by townsend2010 — APPROVED** [review]
Ok, we discussed my question about the `LaunchErrors` thing, so AFAICT, this is good :slightly_smiling_face: 

bors merge

**Comment by townsend2010** [comment]
bors retry

**Review by townsend2010 — CHANGES_REQUESTED** [review]
Looks like integration tests did their job :wink: 
```
ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null cibot@192.168.219.170 -- multipass start --timeout 1200
Warning: Permanently added '192.168.219.170' (ECDSA) to the list of known hosts.
Starting primary  / + _run multipass list
ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null cibot@192.168.219.170 -- multipass list
Warning: Permanently added '192.168.219.170' (ECDSA) to the list of known hosts.
No instances found.
_run multipass exec primary -- uname -a
ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null cibot@192.168.219.170 -- multipass exec primary -- uname -a
Warning: Permanently added '192.168.219.170' (ECDSA) to the list of known hosts.
exec failed: The following errors occurred:
instance "primary" does not exist
exec failed: The following errors occurred:
instance "primary" does not exist
```

So `start` looks like it's returning immediately.

**Review by townsend2010 — APPROVED** [review]
Ok, last commit fixed the issue.  Approving again....

bors merge

**Comment by townsend2010** [comment]
After the unrelated integration test failure, a re-run of the failing test passed: https://github.com/canonical/multipass/actions/runs/4928616452

Going to merge manually...

**Pull request merged**
