### PR TITLE
[qemu] Account for BIOS only Xenial instances

### LINKED ISSUE #2796: [regression][snap] Existing xenial images will not start after upgrading to 1.11.0RC
Upgrading to 1.11.0RC will cause any existing Xenial instances to not boot.  This is due to the `qemu` driver *only* supporting UEFI booting on fresh starts.

Multipass needs to consider existing Xenial instances when starting.

### PR DESCRIPTION
**Pull request by townsend2010**
Fixes #2796

### CODE REVIEW

**Comment by townsend2010** [comment]
Let's see what happens...

bors try

**Review by luis4a0 — APPROVED** [review]
Hey @townsend2010, thanks! LGTM

**Comment by luis4a0** [comment]
Let's rock

bors r+

**Comment by luis4a0** [comment]
A final retry before seeing what's happening

bors retry

**Pull request merged**
