### PR TITLE
[tests] Fix URLDownloader tests

### PR DESCRIPTION
**Pull request by townsend2010**
There is a race that has been showing up on the Windows build.

### CODE REVIEW

**Review by luis4a0 — APPROVED** [review]
Thanks @townsend2010! Increasing the test timeout seems to fix the race condition. If the problem arises again, we can try with a bigger value (10ms is still a very small value which won't compromise speed, in the future we can safely use 50 or 100ms).

**Comment by townsend2010** [comment]
Ugh....

bors retry

**Comment by luis4a0** [comment]
Well, at least it's not windows this time.

bors retry

**Comment by townsend2010** [comment]
If bors fails this time, then let's merge manually.

**Pull request merged**
