### PR TITLE
updated x509 certificates to x509v3 and SANs extension

### PR DESCRIPTION
**Pull request by alexbathome**
# Background

While implementing my own Go client for multipass, I noticed that the TLS certificates used by `multipassd`'s RPC server weren't using the SANs x509v3 extension. 

As such you would run into an annoying error when attempting to verify the TLS certificate that was being returned by the RPC server (`multipassd`). 

Go's standard library hasn't supported TLS/x509 certitficates without SANs present for a while now. See https://go.dev/doc/go1.16#minor_library_changes

# What does this change do? 

This change is a modification to the `ssl_cert_provider.cpp`'s x509 certificate generation. Here there are two major changes: 
1. Version of x509 certificate has been bumped to x509v3
2. Added SANs x509v3 Extension to include `DNS:${server_name}`

# Testing

I have managed to get this building and testing locally on my Ubuntu laptop, however I don't have any additional platforms available to me at the moment. 

The certificate is parsed successfully by `openssl x509 -in <>`  the output looks like:

```
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number: ${BLAH}
        Signature Algorithm: ecdsa-with-SHA256
        Issuer: C = US, O = Canonical, CN = localhost
        Validity
            Not Before: Mar 31 10:42:15 2023 GMT
            Not After : Mar 30 10:42:15 2024 GMT
        Subject: C = US, O = Canonical, CN = localhost
        Subject Public Key Info:d
            Public Key Algorithm: id-ecPublicKey
                Public-Key: (256 bit)
                pub:
                  ${BLAH}
                ASN1 OID: prime256v1
                NIST CURVE: P-256
        X509v3 extensions:
            X509v3 Subject Alternative Name: 
                DNS:localhost
    Signature Algorithm: ecdsa-with-SHA256
    Signature Value:
      ${BLAH}
```

I have also verified the certificate loads correctly using a small GoLang program which simply establishes a connection against the multipassd unix socket.

# Additional notes

If there's any questions, or concerns feel free to drop a comment in, I'm happy to facilitate any modifications to help this get merged :) 

Thanks!

### CODE REVIEW

**Comment by luis4a0** [comment]
Hi @alexbathome, thanks for the code! We value your contribution and we will investigate if it breaks some compatibility with our clients and with the certificates we use. Once confirmed it works, we will consider including it in the next releases.

**Comment by townsend2010** [comment]
Hi @alexbathome!

We are just now able to look at this again.  We still need to ensure that there is no breakage of our current cert with this code.  In the meantime, if you would please sign the [Canonical CLA](https://ubuntu.com/legal/contributors) in order for us to take your contribution.  Let us now when you've done this and we'll move forward!  Thanks!

**Comment by townsend2010** [comment]
Hi @alexbathome!

Just pinging you again since we think this is a valuable contribution and would like to include it in Multipass. :slightly_smiling_face:

**Comment by alexbathome** [comment]
Hi @townsend2010 thanks for the bump! 

I've signed the CLA! Let me know if there's anything more needed to move this forward :rocket:

**Comment by townsend2010** [comment]
Hey @alexbathome!  Awesome, thanks for doing that.  We will review and aim to have it in our upcoming release.

**Comment by townsend2010** [comment]
Hi @alexbathome!

It's failing the CLA check and from what I can tell, it's because the email used for the commit is `no@thank.you` which is not resolving to the Github username.  I don't have any visibility into who has signed the CLA, so I can't manually verify it either :slightly_frowning_face:

**Comment by alexbathome** [comment]
> Hi @alexbathome!
> 
> It's failing the CLA check and from what I can tell, it's because the email used for the commit is `no@thank.you` which is not resolving to the Github username. I don't have any visibility into who has signed the CLA, so I can't manually verify it either 🙁

Ah yes, I didn't set up my git email up on this machine to be contibuting to open source. Leave this with me and I'll sort it out for you shortly :pray:

**Comment by alexbathome** [comment]
@townsend2010 It appears that there's no simple way to amend the author on commits already pushed to a remote like GitHub, (if you do know of a way be sure to let me know.) 

To simplify things I've just re-raised this PR with amended author commits. Please see https://github.com/canonical/multipass/pull/3284

If you're happy with that PR, let's close this one in favour of the new. 

Thanks!

**Comment by townsend2010** [comment]
Closing this in favor of #3284.

**Pull request closed without merging**
