### PR TITLE
Bash completions for the aliases features

### PR DESCRIPTION
**Pull request by luis4a0**
This PR adds completion for the Multipass commands `alias`, `unalias` and `aliases`.

### CODE REVIEW

**Review by townsend2010 — CHANGES_REQUESTED** [review]
So, if I'm in `multipass alias` and I'm tab completing the instance name and choose an instance name and hit tab again, it completes the instance name twice.  For example, if I have an instance named `test`:
`$ multipass alias te`
Hit tab twice and then I get:
`$ multipass alias test:test:`

**Comment by luis4a0** [comment]
Hey @townsend2010! Thanks for the report. It's fixed now. I also added a check to allow only one instance name in the alias 
definition.

**Review by townsend2010 — CHANGES_REQUESTED** [review]
Ok, the `alias` and `aliases` completions like fine. However, I think `unalias` should bash complete the alias names as well.

**Comment by luis4a0** [comment]
Oh, I must have forgotten `unalias`!

Done, it's implemented now.

**Review by townsend2010 — APPROVED** [review]
Ok, LGTM.  Thanks!

bors merge

**Comment by townsend2010** [comment]
Hmm, some weird build error.  Try again...

bors retry

**Comment by townsend2010** [comment]
Urg, again...

bors retry

**Pull request merged**
