### PR TITLE
[qemu] Fix crash on concurrent shutdown

### PR DESCRIPTION
**Pull request by ricab**

### CODE REVIEW

**Review by townsend2010 — APPROVED** [review]
LGTM, thanks!

bors merge

**Comment by townsend2010** [comment]
bors merge

**Comment by ricab** [comment]
FWIW, I restarted the build that failed and it succeeded. The last missing build (win11) is running here: https://github.com/canonical/multipass/actions/runs/5397356920

**Comment by townsend2010** [comment]
Ok, this passed the integration tests.  Will merge manually.

**Pull request merged**
