### PR TITLE
Fix compilation with Clang 12 on Linux.

### PR DESCRIPTION
**Pull request by luis4a0**
Clang is picky with lambda captures.

### CODE REVIEW

**Review by ricab — APPROVED** [review]
Yeah, it's a pain that we can't capture structured bindings (until C++20 I think). FWIW, you can still use regular vars, to conserve the names and avoid repeating `get<>` if you need them more than once:

```c++
    const auto& param = GetParam();
    const auto& expected_firewall = std::get<0>(param);
    ...
```

It's perhaps not too relevant here though, so accepting.

bors r+

**Comment by Saviq** [comment]
bors retry

**Comment by Saviq** [comment]
bors merge

**Comment by Saviq** [comment]
bors r=ricab

**Comment by ricab** [comment]
Oh dear.

bors r+

**Comment by luis4a0** [comment]
Let's retry... there is a couple of combinations backend/platform which still didn't fail. Come on CI, go for it! :joy:

**Comment by ricab** [comment]
Sure, here goes

bors r+

**Pull request merged**
