### PR TITLE
Sanitize optional derefs

### PR DESCRIPTION
**Pull request by ricab**
---

Only test code affected after all.

~~Requires #1331 to be merged. Change base to master and delete ghost branch ATP.~~

### CODE REVIEW

**Comment by Saviq** [comment]
This has to be adapted due to canonical/multipass#1392.

**Comment by ricab** [comment]
@Saviq Done, adapted by removing all `value()` calls and replacing with asserts (they were in tests).

**Comment by Saviq** [comment]
bors cancel

**Comment by ricab** [comment]
@Saviq this should be finally ready. Sorry for the noise.

**Comment by Saviq** [comment]
No worries :)

bors r+

**Comment by Saviq** [comment]
Hmm?

bors r+

**Pull request merged**
