### PR TITLE
Release 1.1.0

### PR DESCRIPTION
**Pull request by Saviq**
---

Diff from master: https://paste.ubuntu.com/p/3P4BKf9q44/

### CODE REVIEW

**Comment by ricab** [comment]
@Saviq Would you cherry-pick the new commit into master? 

Maybe we can have Travis test this but then get it in a regular PR, merged into master, and cherry-pick that into the release branch, as usual? If it is still just a small change and Travis does the right thing here, send it my way and I'll approve when I see it (=tomorrow).

**Comment by townsend2010** [comment]
I tested the Mac package and all seems well.  That said, as mentioned on IRC, I'd like to set a new minimum OSX version.  Since we build on a `10.13` machine, I thought we should set the minimum version to that.  However, https://github.com/canonical/multipass/issues/1258#issuecomment-587455490 seems to indicate that `10.14` is the minimum, but it is not clear to me where that comes from.

**Comment by townsend2010** [comment]
As an aside, I tried `snap refresh multipass --channel candidate/1.1` per the instructions above and I get:
```
error: requested a non-existing branch on latest/candidate for snap "multipass": 1.1
```

**Comment by marcodelapierre** [comment]
Just tested the rc on a mac, to test for a terminal resizing issue I had with 1.0.
The release candidate has fixed my issue.
(see also my comment in #1370 )

**Comment by Saviq** [comment]
> ```
> error: requested a non-existing branch on latest/candidate for snap "multipass": 1.1
> ```

Fixed: 79004a6

**Comment by Saviq** [comment]
I've tested all of [the v1.1.0 milestone](https://github.com/canonical/multipass/milestone/7?closed=1) on Linux (and the other platforms, where the issue was platform-specific) and confirmed it all worked, didn't see any new issues.

Refreshing from `stable` to `candidate/1.1` also works, recovering instance state.

**Comment by NickZ** [comment]
Issue #1170 is still present in this build: https://github.com/canonical/multipass/issues/1170#issuecomment-593051354

**Pull request merged**
