### PR TITLE
[submodule] Update grpc to v1.52.1

### LINKED ISSUE #2927: Update gRPC to v1.52.1
Version 1.52.1 is the latest version at the time of this writing.

### PR DESCRIPTION
**Pull request by townsend2010**
Fixes #2927

### CODE REVIEW

**Comment by ricab** [comment]
Is #2435 no longer applicable or desired?

**Comment by townsend2010** [comment]
Hey @ricab!

> Is https://github.com/canonical/multipass/pull/2435 no longer applicable or desired?

Well, *I* think it's still applicable, but no one reviewed it in the year since it was proposed, so I didn't think there was much interest in that and I didn't push for it either since it's not critical.  If you think that PR is helpful, then I can update it instead and someone can review it soon.

**Comment by ricab** [comment]
OK, thanks for clarifying. I propose we discuss it today and make a decision one way or the other.

**Comment by townsend2010** [comment]
After a team discussion, I will update #2435 instead and that will get reviewed.

**Pull request closed without merging**
