### PR TITLE
Confirm snapshot deletion with prompt

### PR DESCRIPTION
**Pull request by ricab**
Confirm snapshot deletion with a prompt to users when they try to delete a snapshot without the `--purge` flag, as long as multipass is running interactively.

### CODE REVIEW

**Comment by ricab** [comment]
Note that this is stacked on #3287 .

**Comment by luis4a0** [comment]
Hey @ricab, thanks for this! Code looks nice, just a bit of manual testing and we're ready to go.

**Comment by ricab** [comment]
Hey @luis4a0, thank you for the review!

We've been following the "convention" of using a capital letter for the default answer. With quotes because I am not sure how conventional it actually is, but I have seen it in different places. When there is no default, it is better to use just "yes/no" (as in the bridging question). Hope that makes sense :slightly_smiling_face:

**Comment by luis4a0** [comment]
@ricab that makes complete sense, I didn't know about the convention. That's all I had. Thanks!

**Review by luis4a0 — APPROVED** [review]

**Pull request merged**
