### PR TITLE
[tests] stop installing gtest

### PR DESCRIPTION
**Pull request by Saviq**

### CODE REVIEW

**Comment by ricab** [comment]
Anything blocking this?

**Comment by townsend2010** [comment]
@ricab,

Nothing blocking per se, but it didn't look like it did what it was supposed to do and so @Saviq put in https://github.com/canonical/multipass-private/pull/461 instead.  Not sure why this didn't work, so I was reluctant to just close until we understood why.

**Comment by ricab** [comment]
Got it, thanks for explaining.

**Comment by Saviq** [comment]
Well, it's still correct to do in our case (as we don't package anything GTest).

**Review by townsend2010 — APPROVED** [review]
Ok, makes sense to use this.

bors merge

**Pull request merged**
