### PR TITLE
Fix discard warning

### PR DESCRIPTION
**Pull request by ricab**
I noticed MSVC complaining about this:

```
Z:\src\platform\backends\shared/base_vm_image_vault.h(63): warning C4834: discarding return value of function with 'nodiscard' attribute
```

### CODE REVIEW

**Review by townsend2010 — APPROVED** [review]
Yep, makes sense.  Thanks!

bors merge

**Comment by townsend2010** [comment]
bors merge

**Comment by townsend2010** [comment]
bors merge

**Comment by townsend2010** [comment]
Try again:

bors merge

**Comment by ricab** [comment]
Thanks @townsend2010, I think bors missed the memo.

bors ping

**Comment by townsend2010** [comment]
@ricab, bors is currently running at the time of this comment.

**Comment by ricab** [comment]
Ah thank you, I wasn't sure anymore.

**Pull request merged**
