### PR TITLE
[gha] trigger on "Ready for review"

### PR DESCRIPTION
**Pull request by Saviq**

### CODE REVIEW

**Review by ricab — COMMENTED** [review]
Why on Linux? Does this make sense when it would have already run on drafts?

**Comment by Saviq** [comment]
> Why on Linux? Does this make sense when it would have already run on drafts?

Because of this, which just landed:

https://github.com/canonical/multipass/blob/346644970903bac0fe4e7d15caf550374dca7d03/.github/workflows/linux.yml#L216-L231

We need the dispatch to know when it's out of draft.

**Review by ricab — APPROVED** [review]
Yep.

bors r+

**Comment by ricab** [comment]
bors retry

**Pull request merged**
