### PR TITLE
[snapcraft] use buildd images across the board

### PR DESCRIPTION
**Pull request by Saviq**

### CODE REVIEW

**Comment by Saviq** [comment]
bors try

**Comment by Saviq** [comment]
bors try

**Comment by Saviq** [comment]
bors try

**Comment by Saviq** [comment]
bors try

**Comment by Saviq** [comment]
bors try

**Comment by Saviq** [comment]
CI using b109324 succeeded:
- [Linux](https://github.com/canonical/multipass/actions/runs/755605380)
- [macOS](https://github.com/canonical/multipass/actions/runs/755604031)
- [Windows](https://github.com/canonical/multipass/actions/runs/755606814)

**Comment by ricab** [comment]
Is this pending review or something else?

**Comment by Saviq** [comment]
> Is this pending review or something else?

Needs a refresh and verification that it indeed works, I'll remove the `no-merge` label when it's ready.

**Pull request closed without merging**
