### PR TITLE
[gui] Update available multiple msgs bugfix

### PR DESCRIPTION
**Pull request by surahman**
**_Issue #2188:_**
Introducing a check for signal connection to the GUI when an update is available.

We could also, potentially, do the following and move the `disconnect` from the `else` statement out to before the update check - which is what you suggested. It is the same code as the original, but just refactored:
```c++
void cmd::GuiCmd::update_about_menu()
{
    auto reply = version_future.result();

    about_client_version.setText("multipass version: " + QString::fromStdString(multipass::version_string));
    about_daemon_version.setText("multipassd version: " + QString::fromStdString(reply.version()));

    QObject::disconnect(&tray_icon, &QSystemTrayIcon::messageClicked, 0, 0);
    tray_icon_menu.removeAction(&update_action);

    if (update_available(reply.update_info()))
    {
        update_action.setIcon(QApplication::style()->standardIcon(QStyle::SP_MessageBoxInformation));
        update_action.setWhatsThis(QString::fromStdString(reply.update_info().url()));

        QObject::connect(&tray_icon, &QSystemTrayIcon::messageClicked,
                         [this] { QDesktopServices::openUrl(QUrl(update_action.whatsThis())); });

        tray_icon_menu.insertAction(about_menu.menuAction(), &update_action);
        tray_icon.showMessage(QString::fromStdString(reply.update_info().title()),
                              QString("%1\n\nClick here for more information.")
                                  .arg(QString::fromStdString(reply.update_info().description())));
    }
}
```

My rationale for performing the check to see if there is a connected signal is because it might be more efficient than a potentially needless attempt to disconnect. I am open to suggestions and the above code is sitting on the `dev` branch waiting to be merged if required.

### CODE REVIEW

**Review by ricab — CHANGES_REQUESTED** [review]
Hi @surahman, unfortunately this doesn't work [because](https://doc.qt.io/qt-5/qobject.html#isSignalConnected):

> signal must be a signal member of this object, otherwise the behaviour is undefined.

Can't call it on `tray_icon` either because it's protected. But your alternative of always disconnecting should work. Want to commit it?

**Comment by surahman** [comment]
Hi @ricab, sorry about the multiple commits, the refactored code has been pushed.

**Comment by surahman** [comment]
Sorry, cleaned up the commit history.

**Review by ricab — APPROVED** [review]
Yep, that fixes it! Thanks a lot @surahman :+1: 

bors r+

**Comment by surahman** [comment]
Thanks for reviewing @ricab!

**Pull request merged**
