### PR TITLE
ci: wait for daemon to restart in integration

### PR DESCRIPTION
**Pull request by Saviq**

### CODE REVIEW

**Comment by Saviq** [comment]
This passed here:

https://github.com/canonical/multipass/actions/runs/3199007889/jobs/5224260971

When the same on `main` failed just a few minutes before:

https://github.com/canonical/multipass/actions/runs/3198976531/jobs/5224188137

**Comment by Saviq** [comment]
For kicks.

bors try

**Comment by Saviq** [comment]
> This passed here

And 12 times in a loop locally.

**Review by townsend2010 — APPROVED** [review]
LGTM, thanks!

bors merge

**Comment by townsend2010** [comment]
bors retry

**Comment by townsend2010** [comment]
bors merge

**Pull request merged**
