### PR TITLE
[subcmd] Forward verbosity to subcmds

### LINKED ISSUE #1550: Verbosity lost when working with the primary instance
**Describe the bug**
When working with the primary instance (`mutlipass shell` exposes it the most, if primary doesn't exist), the selected verbosity is lost when invoking subcommands (like `launch`, `start`, `mount`).

**To Reproduce**
How, and what happened?
1. `multipass delete -p primary`
1. `multipass shell -vvv`

**Expected behavior**
Verbose logging.

**Logs**
N/A

**Additional info**
 - OS: N/A
- `multipass 1.2.0`

### PR DESCRIPTION
**Pull request by ricab**
Fixes #1550.

### CODE REVIEW

**Comment by ricab** [comment]
Unfortunately this is not playing well with something

```
/E0529 18:15:10.656399660   59826 ssl_transport_security.cc:483] Corruption detected.
E0529 18:15:10.656415748   59826 ssl_transport_security.cc:459] error:1e000065:Cipher functions:OPENSSL_internal:BAD_DECRYPT
E0529 18:15:10.656422831   59826 ssl_transport_security.cc:459] error:1000008b:SSL routines:OPENSSL_internal:DECRYPTION_FAILED_OR_BAD_RECORD_MAC
E0529 18:15:10.656428523   59826 secure_endpoint.cc:208]     Decryption error: TSI_DATA_CORRUPTED
E0529 18:15:10.656447885   59826 ssl_transport_security.cc:510] SSL_write failed with error SSL_ERRORmount failed: Stream removed
```

**Comment by ricab** [comment]
It turns out the problems mentioned above are actually a pre-existing issue: #1570, so this is ready for review.

**Comment by Saviq** [comment]
Looks good, and works :)

bors merge

**Comment by ricab** [comment]
hmm trouble getting snaps in builds...

bors retry

**Comment by Saviq** [comment]
Store was down.

bors retry

**Comment by Saviq** [comment]
Once more, with feeling…

bors merge

**Pull request merged**
