### PR TITLE
[qemu] catch possible errors when syncing hw clock

### LINKED ISSUE #3394: VM fails to complete start from a suspended state
**Describe the bug**
The VM starts, but before the start RPC is finished, Multipass tries to sync its clock and there is an exception that goes through Qt code, leaving the daemon in a bad state.

**To Reproduce**
How, and what happened?
1. `multipass launch -n foo`
1. `multipass suspend foo`
2. `multipass start foo`

The last command will keep spinning. After a ctrl+c, I can't reach the daemon anymore:

```
$ multipass ls
list failed: cannot connect to the multipass socket
```

**Logs**

The relevant portion is:
```
jan 31 17:31:36 ricab-XPS-9320 multipassd[410242]: VM suspended
jan 31 17:31:36 ricab-XPS-9320 multipassd[410242]: process state changed to NotRunning
jan 31 17:31:36 ricab-XPS-9320 multipassd[410242]: Suspended VM successfully stopped
jan 31 17:31:41 ricab-XPS-9320 multipassd[410242]: process working dir '/snap/multipass/11600/qemu'
jan 31 17:31:41 ricab-XPS-9320 multipassd[410242]: process program 'qemu-system-x86_64'
jan 31 17:31:41 ricab-XPS-9320 multipassd[410242]: process arguments '-bios, OVMF.fd, --enable-kvm, -cpu, host, -nic, tap,ifname=tap-4137086f43c,script=no,downscript=no,model=virtio-net-pci,mac=52:54:00:aa:11:26, -device, virtio-scsi-pci,id=scsi0, -drive, file=/var/snap/multipass/common/data/multipassd/vault/instances/natural-redbird/ubuntu-22.04-server-cloudimg-amd64.img,if=none,format=qcow2,discard=unmap,id=hda, -device, scsi-hd,drive=hda,bus=scsi0.0, -smp, 1, -m, 1024M, -qmp, stdio, -chardev, null,id=char0, -serial, chardev:char0, -nographic, -cdrom, /var/snap/multipass/common/data/multipassd/vault/instances/natural-redbird/cloud-init-config.iso, -loadvm, suspend, -machine, pc-i440fx-8.0'
jan 31 17:31:41 ricab-XPS-9320 multipassd[410242]: Resuming from a suspended state
jan 31 17:31:41 ricab-XPS-9320 multipassd[410242]: Applied AppArmor policy: multipass.natural-redbird.qemu-system-x86_64
jan 31 17:31:41 ricab-XPS-9320 multipassd[410242]: process state changed to Starting
jan 31 17:31:41 ricab-XPS-9320 multipassd[410242]: process state changed to Running
jan 31 17:31:41 ricab-XPS-9320 multipassd[410242]: [411184] started: qemu-system-x86_64 -bios OVMF.fd --enable-kvm -cpu host -nic tap,ifname=tap-4137086f43c,script=no,downscript=no,model=virtio-net-pci,mac=52:54:00:aa:11:26 -device virtio-scsi-pci,id=scsi0 -drive file=/var/snap/multipass/common/data/multipassd/vault/instances/natural-redbird/ubuntu-22.04-server-cloudimg-amd64.img,if=none,format=qcow2,discard=unmap,id=hda -device scsi-hd,drive=hda,bus=scsi0.0 -smp 1 -m 1024M -qmp stdio -chardev null,id=char0 -serial chardev:char0 -nographic -cdrom /var/snap/multipass/common/data/multipassd/vault/instances/natural-redbird/cloud-init-config.iso -loadvm suspend -machine pc-i440fx-8.0
jan 31 17:31:41 ricab-XPS-9320 multipassd[410242]: process started
jan 31 17:31:41 ricab-XPS-9320 multipassd[410242]: Waiting for SSH to be up
jan 31 17:31:41 ricab-XPS-9320 multipassd[410242]: QMP: {"QMP": {"version": {"qemu": {"micro": 0, "minor": 0, "major": 8}, "package": ""}, "capabilities": ["oob"]}}
jan 31 17:31:42 ricab-XPS-9320 multipassd[410242]: QMP: {"return": {}}
jan 31 17:31:42 ricab-XPS-9320 multipassd[410242]: Deleted memory snapshot
jan 31 17:31:42 ricab-XPS-9320 multipassd[410242]: Syncing RTC clock
jan 31 17:31:42 ricab-XPS-9320 multipassd[410242]: Executing 'sudo hwclock --hctosys'
jan 31 17:31:47 ricab-XPS-9320 multipassd[410242]: Qt has caught an exception thrown from an event handler. Throwing
                                                   exceptions from an event handler is not supported in Qt.
                                                   You must not let any exception whatsoever propagate through Qt code.
```

**Additional info**
- OS: Ubuntu
- `multipass version`: `1.14.0-dev.1258+gd28626a9`
- `multipass get local.driver`: `qemu`
- First hit on macOS with a related (1.14...) version.

### PR DESCRIPTION
**Pull request by sharder996**
Fixes #3394

### CODE REVIEW

**Review by ricab — COMMENTED** [review]
OK, this fixes the failure to start:

```
fev 02 12:10:17 multipassd[46419]: Deleted memory snapshot
fev 02 12:10:17 multipassd[46419]: Syncing RTC clock
fev 02 12:10:17 multipassd[46419]: Executing 'sudo hwclock --hctosys'
fev 02 12:10:22 multipassd[46419]: Failed to sync clock: failed to obtain exit status for remote process 'sudo hwclock --hctosys': timeout
```

However, that clock sync command always fails for me:

```
$ multipass exec secure-platy -- sudo hwclock --hctosys
hwclock: select() to /dev/rtc0 to wait for clock tick timed out
```

Sometimes the time sync works, sometimes it doesn't:

```
$ date && multipass exec secure-platy -- date && date
sex 02 fev 2024 12:15:45 WET
Fri Feb  2 12:15:37 WET 2024
sex 02 fev 2024 12:15:45 WET
[...]
$ date && multipass exec secure-platy -- date && date
sex 02 fev 2024 12:18:41 WET
Fri Feb  2 12:18:41 WET 2024
sex 02 fev 2024 12:18:41 WET
```


I imagine there will be others in the same situation. Do you have any insight into why this happens and if there is anything else we could do without delaying startup?

**Comment by sharder996** [comment]
What is the output of:
```
multipass exec secure-platy -- sudo hwclock --hctosys --directisa --verbose
```

It looks like this is a hardware issue specific to your host machine which explains why Chris and I never experienced it.

**Comment by ricab** [comment]
Here's what I get when executing that right after exception is caught:

```
$ multipass exec secure-platy -- sudo hwclock --hctosys --directisa --verbose
hwclock from util-linux 2.37.2
System Time: 1706889438.995315
Using direct ISA access to the clock
Assuming hardware clock is kept in UTC time.
Waiting for clock tick...
...got clock tick
Time read from Hardware Clock: 2024/02/02 15:57:19
Hw clock time : 2024/02/02 15:57:19 = 1706889439 seconds since 1969
Time since last adjustment is 1706889439 seconds
Calculated Hardware Clock drift is 0.000000 seconds
Calling settimeofday(NULL, 0) to lock the warp_clock function.
Calling settimeofday(1706889439.000000, NULL) to set the System time.
```

The time appears to be in sync after that.

**Comment by ricab** [comment]
Although the clock seems to get back in sync on its own after waiting for a while.

**Comment by ricab** [comment]
When I execute the command that Multipass uses outside an instance, it immediately succeeds.

**Comment by ricab** [comment]
Well, I am not sure what the difference is in my case. QEMU has options related to the clock, but:

> By default the RTC is driven by the host system time. This allows using of the  RTC as accurate reference clock inside the guest, specifically if the host time is smoothly following an accurate external reference clock, e.g. via NTP.

I have tried disabling "automatic date & time" in gnome settings but it didn't make a difference.

**Review by ricab — COMMENTED** [review]
OK, I think we can stick with this approach right now. If we ever find what causes RTC timeouts, we can address them separately.

Concerning tests, how difficult do you think it would be to get some coverage on this? Do you think the existing (pre)mock SSH facilities are up to the task, or do they make it too difficult? We should really have a proper way to mock SSH stuff at a higher level, but that's for another time.

**Comment by sharder996** [comment]
While testing I found another problem that will show up in the future. The `util-linux-extra` package which contains the `hwclock` command is not included in base ubuntu from mantic onwards.

This command might be better then:
```
sudo timedatectl set-local-rtc 0 --adjust-system-clock
```
Does this work on your instance where `hwclock` did not? Or any insight into whether this is a better option? From the man page it looks like this command does what we want.

**Comment by ricab** [comment]
That worked fine for me! And it is part of the systemd suite, so it is pretty standard and probably a better choice.

**Comment by sharder996** [comment]
I took a look at what it would take to get this covered in unit tests and I think there would be a bit of initial overhead. We don't have anything set up for mocking `SSHSession` and we also don't have anything set up for testing backend specific virtual machine classes. If it's not too big of a deal, I think we leave it for another time.

Leaving the try-catch block still seems like a good idea so that we don't crash the daemon if the command fails.

**Comment by townsend2010** [comment]
Hey @sharder996,

Although we don't mock `SSHSession` directly since it's neither an injectable singleton nor a passed in mockable class, it is possible to mock the underlying `libssh` calls.  We do this in many places in the tests, so there are many examples.

That said, we aren't testing *any* of the signal/slot connections in the `QemuVirtualMachine` ctor and it appears to be tricky to do so, so I'm ok with deferring any unit tests here.

**Review by ricab — APPROVED** [review]
Alright, thank you for this @sharder996!

**Pull request merged**
