### PR TITLE
[tests] Wait on Daemon slot thread when it quits

### LINKED ISSUE #2886: [tests] Random segfault in unit tests
When running CI, we occasionally see segfaults in unit tests on Linux and Windows builds.

After some investigation, these happen during `Daemon`-related tests, ie, anything using the `DaemonTestFixture` class.

### PR DESCRIPTION
**Pull request by townsend2010**
Fixes #2886

### CODE REVIEW

**Review by ricab — APPROVED** [review]
It looks like this needs a rebase, but other than that it LGTM, thanks!

**Comment by townsend2010** [comment]
Thanks @ricab!  I rebased and once that builds, I'll `bors` it with you as the approver.

**Comment by ricab** [comment]
Sounds good, thanks!

bors d+

**Comment by townsend2010** [comment]
bors r=ricab

**Pull request merged**
