### PR TITLE
[auth] fix authentication

### PR DESCRIPTION
**Pull request by Saviq**

### CODE REVIEW

**Comment by townsend2010** [comment]
Fails lint...

**Review by townsend2010 — APPROVED** [review]
Ok, this is fine a workaround until all of the new settings stuff is in place.

bors merge

**Comment by Saviq** [comment]
bora retry

**Comment by townsend2010** [comment]
lol at https://github.com/canonical/multipass/pull/2471#issuecomment-1059211506

bors retry

**Comment by Saviq** [comment]
The other side of CI got stuck…

bors merge

**Comment by townsend2010** [comment]
Try again...

bors merge

**Comment by Saviq** [comment]
Will you?

bors merge

**Pull request merged**
