### PR TITLE
[daemon] add `multipass` group support

### PR DESCRIPTION
**Pull request by Saviq**

### CODE REVIEW

**Comment by townsend2010** [comment]
Hey @Saviq,

What is the motivation for this change?  I thought a long time ago, we agreed not to support a `multipass` group...

**Comment by Saviq** [comment]
The motivation is that if someone wants to, and has created the group, we'll use it.

We don't want to go about managing the group, but if it's there…

Driver was KDE folks building snaps in CI - they'd rather not use `sudo`.

**Comment by townsend2010** [comment]
Ok, I see no harm in that.  Will approve them :smiley:

**Review by townsend2010 — APPROVED** [review]
Ok, makes sense if someone adds a `multipass` group.

bors merge

**Comment by Saviq** [comment]
_Actually_ I thought of it more and felt it's giving a false sense of security. You could mount and edit the host's `/etc/sudoers` and gain root this way.

**Pull request closed without merging**
