### PR TITLE
[shared] unify image conversion timeouts (Fixes #1746)

### LINKED ISSUE #1746: multipass launch failed with qemu-img error on Win 10 home
I am trying to launch the  multipass from windows 10 Home.

 multipass set local.driver=virtualbox   was ok
C:\WINDOWS\system32> multipass --version
multipass  1.4.0+win
multipassd 1.4.0+win
C:\WINDOWS\system32> multipass launch
launch failed: Conversion of image to VDI failed (program: qemu-img; error: Process operation timed out) with the following output:

I tried these command on powershell using admin right. please advise on the launch failed

### PR DESCRIPTION
**Pull request by Saviq**

### CODE REVIEW

**Review by townsend2010 — APPROVED** [review]
LGTM, thanks!

bors merge

**Comment by Saviq** [comment]
> Build failed:
> 
>     * [continuous-integration/travis-ci/push](https://travis-ci.org/github/canonical/multipass/builds/728978730?utm_source=github_status&utm_medium=notification)

I know! It's fixed already ;P

**Comment by Saviq** [comment]
bors r=townsend2010

**Comment by townsend2010** [comment]
Ok, try it one more time:
bors merge

**Pull request merged**
