### PR TITLE
[snapcraft] add `core20` support

### PR DESCRIPTION
**Pull request by Saviq**

### CODE REVIEW

**Comment by Saviq** [comment]
> macOS build available: [multipass-1.5.0-dev.334.pr1213+g67f2dd96.mac-Darwin.pkg](https://multipass-ci.s3.amazonaws.com/pr1213/multipass-1.5.0-dev.334.pr1213%2Bg67f2dd96.mac-Darwin.pkg)

macOS w/ VirtualBox:
```
$ multipass ls
Name                    State             IPv4             Image
assuring-deerhound      Running           N/A              Ubuntu Snapcraft builder for Core 18
ecstatic-waxwing        Running           N/A              Ubuntu Snapcraft builder for Core 16
satisfying-mongrel      Running           N/A              Ubuntu Snapcraft builder for Core 20
```

macOS w/ hyperkit:
```
$ multipass ls
Name                    State             IPv4             Image
happy-terrier           Running           192.168.64.36    Ubuntu Snapcraft builder for Core 18
intense-waterbear       Running           192.168.64.37    Ubuntu Snapcraft builder for Core 16
plausible-jaeger        Running           192.168.64.38    Ubuntu Snapcraft builder for Core 20
```

**Comment by townsend2010** [comment]
> Snap build available: `snap refresh multipass --channel edge/pr1213`

Snap w/ qemu:
```
$ multipass list
Name                    State             IPv4             Image
enjoyed-pigeon          Running           10.111.86.246    Ubuntu Snapcraft builder for Core 16
gifted-wapiti           Running           10.111.86.106    Ubuntu Snapcraft builder for Core 18
immediate-greyhound     Running           10.111.86.253    Ubuntu Snapcraft builder for Core 20
```

Snap w/ libvirt:
```
$ multipass list
Name                    State             IPv4             Image
cunning-passerine       Running           192.168.122.182  Ubuntu Snapcraft builder for Core 20
nice-grackle            Running           192.168.122.156  Ubuntu Snapcraft builder for Core 18
psychic-kea             Running           192.168.122.240  Ubuntu Snapcraft builder for Core 16
```

Snap w/ lxd:
"No shirt. No shoes. NO DICE."

**Comment by Saviq** [comment]
> What's the status on this? Is core20 still not working with lxd?

If you're asking about the LXD backend of Multipass, then we're working on enabling `snapcraft:` images on it right now, it's coming soon.

**Comment by sergiusens** [comment]
This update works well on os x

**Pull request closed without merging**
