### PR TITLE
Fix Qt warning

### PR DESCRIPTION
**Pull request by ricab**
Avoid setting permissions on an empty dir. Also, let new storage dirs inherit permissions.

### CODE REVIEW

**Comment by ricab** [comment]
Hey @sharder996, does this look alright to you? I know you worked on this ~recently. I moved permissions-setting on `storage_path` so that new sub-directories can inherit them.

**Review by sharder996 — COMMENTED** [review]
Hey @ricab, what was the warning that Qt was giving you? Regardless, two things that I noticed:
- The order to setting permissions and creating the cache/data directory shouldn't matter because of permissions inheritance. I haven't checked this, but maybe the ordering fixes your warning.
- I avoided using `if (!storage_path.isEmpty())` when setting permissions the first time around because the permissions should be set regardless (eg. we want to overwrite/update permissions for an existing installation of Multipass when a user chooses to keep their data).

**Comment by ricab** [comment]
Hey @sharder996, so the warning is the one in issue #3010. It was in a commit message and I am not sure why GH is not linking it properly...

The order change was a drive-by thing, just because I noticed that data and cache directories would be created before setting the permissions on the parent, and so I thought they wouldn't inherit them (unless that function operates recursively?). 

The `if (!storage_path.isEmpty())` part was where the actual fix was. Without it, we were trying to set permissions on the path `""`, which would trigger the warning by Qt.

**Comment by ricab** [comment]
OK, I made this address only the warning for the empty filename. #3013 addresses the ordering.

**Review by sharder996 — APPROVED** [review]
LGTM
bors merge

**Comment by sharder996** [comment]
bors retry

**Comment by sharder996** [comment]
one more time

bors retry

**Comment by ricab** [comment]
Hey @sharder996, is that last merge intentional?

**Comment by sharder996** [comment]
bors merge

**Pull request merged**
