### PR TITLE
Singleton consts

### PR DESCRIPTION
**Pull request by ricab**
Add missing `const`s to singleton methods. I left a couple of conceptual exceptions untouched, like `Utils::exit` or `Settings::set`. The latter would allow caching without changing the interface.

### CODE REVIEW

**Review by townsend2010 — APPROVED** [review]
This looks good, but conflicts need fixing.  Once that's done, we can get it in.

**Comment by ricab** [comment]
Thank you @townsend2010, I'll leave that for next week.

**Comment by ricab** [comment]
Done @townsend2010 (here and on the other side). Thanks.

**Review by townsend2010 — APPROVED** [review]
LGTM, thanks!

bors merge

**Pull request merged**
