### PR TITLE
ci: drop `**` from ccache `path:`

### PR DESCRIPTION
**Pull request by Saviq**
Having this resulted in 4 copies of the same file in my work with Mir…

While here, upgrade the action.

Signed-off-by: Michał Sawicz <michal.sawicz@canonical.com>

### CODE REVIEW

**Comment by townsend2010** [comment]
bors merge

**Comment by townsend2010** [comment]
bors retry

**Comment by Saviq** [comment]
Maybe it likes me more…

bors retry

**Comment by townsend2010** [comment]
> Maybe it likes me more…

I really hope it does :crossed_fingers:

**Comment by Saviq** [comment]
Not funny.

bors retry

**Comment by townsend2010** [comment]
Ok, well, Windows integration tests have been failing reliably lately.  Will merge this manually.

**Pull request merged**
