### PR TITLE
[ci] make the renovate bot run only every 2 weeks

### PR DESCRIPTION
**Pull request by andrei-toterman**
This PR makes the renovate bot run only every two weeks on Monday, and it also moves the config file to JSON5 so that it can support trailing commas.

### CODE REVIEW

**Review by sharder996 — APPROVED** [review]
LGTM!

**Review by ricab — COMMENTED** [review]
Did you test this somehow? And why the move to JSON5 (for my understanding)?

**Comment by andrei-toterman** [comment]
@ricab I updated the PR description to mention that the move to JSON5 was just so that the file can support trailing commas. Not a necessity, but IMO it would be nice in the future if we need to add more config options, to not have to worry about that last comma.

As for testing, I ran `npx --yes --package renovate -- renovate-config-validator` and it passed the validation. Of course, I also ran that validation with a small mistake in the file to make sure it actually accepts only the right stuff :) But I can't really be sure how the actual bot will behave now, we'll just have to wait to see, as I don't really know if and how we can test the actual bot.

**Comment by andrei-toterman** [comment]
Also, in the docs they mention that they use the `@breejs/later` npm package to parse that schedule string, and I played with it locally a bit and it could parse my string.

**Review by ricab — APPROVED** [review]
Perfect, thanks for the clarifications!

**Comment by ricab** [comment]
> @ricab https://docs.renovatebot.com/presets-schedule/#schedulequarterly
> 
> As a similar example

Yep, I'd seen that, but I wasn't sure if it could do "on monday".

**Pull request merged**
