### PR TITLE
[backends/lxd] Ensure LXD is configured and ready at daemon start time

### LINKED ISSUE #2401: Creating instance with LXD fails after snap refresh
**Describe the bug**
After succesfully creating an instance, trying to create a new one failed.

**To Reproduce**
This situation showed up randomly, I'm not sure how to reproduce. In my case, I first created a VM with
`multipass launch -c 1 -d 10G -n testfs1lxd`

Then, trying to create a new one with
`multipass launch -c 4 -d 10G -n testfs4lxd`
gave
```
[2022-01-20T14:34:55.777] [error] [lxd request] Operation completed with error: (400) Failed creating instance record: Invalid devices: Device validation failed for "root": Root disk entry must have a "pool" property set
launch failed: Operation completed with error: (400) Failed creating instance record: Invalid devices: Device validation failed for "root": Root disk entry must have a "pool" property set
```

**Expected behavior**
A new instance running would be expected. However, `multipass list` shows the new instance in `unknown` state.

**Logs**
[Here](https://pastebin.ubuntu.com/p/hNCGCf6mvF/)

**Additional info**
Ubuntu 21.10
```
multipass version
multipass   1.9.0-dev.338+ga1ea65fb
```

**Additional context**
```
lxd --version
4.22
```

### PR DESCRIPTION
**Pull request by townsend2010**
Fixes #2401

### CODE REVIEW

**Comment by Saviq** [comment]
This seems a bit naive, shouldn't all drivers be treated the same? Or at least those where something else actually manages the VMs?

**Comment by townsend2010** [comment]
> This seems a bit naive, shouldn't all drivers be treated the same? Or at least those where something else actually manages the VMs?

Yes, I think they should.  But I think other backends are out of the scope of this particular PR.

**Comment by Saviq** [comment]
> Yes, I think they should. But I think other backends are out of the scope of this particular PR.

I just worry this will mean just kicking it down the line until we encounter another bug. We should at least have a TODO or an issue filed.

**Comment by townsend2010** [comment]
Closing this in favor of #2406

**Pull request closed without merging**
