### PR TITLE
[image_host/custom] Point snapcraft:devel to lunar buildd daily

### LINKED ISSUE #3017: Switch snapcraft:devel to point to Lunar buildd daily build

### PR DESCRIPTION
**Pull request by townsend2010**
Fixes #3017

### CODE REVIEW

**Review by sharder996 — APPROVED** [review]
LGTM!

**Comment by sharder996** [comment]
bors merge

**Comment by sharder996** [comment]
bors retry

**Comment by townsend2010** [comment]
A subsequent run of integration tests passed, so I'm just going to merge this.

**Pull request merged**
