### PR TITLE
[cli] Remove padded chars in cli output

### LINKED ISSUE #958: `multipass launch` pads its output to 80 characters with whitespace
You can't _see_ this per se, but copying/pasting whole lines from my console demonstrates the problem:

```shell
% multipass launch bionic
Launched: steady-koel                                                           
```

```python3
>>> len("Launched: steady-koel                                                           ")
80
```

I would expect no trailing whitespace.

### PR DESCRIPTION
**Pull request by sharder996**
Use [ANSI escape characters](https://gist.github.com/fnky/458719343aabd01cfb17a3a4f7296797) to manipulate cursor and overwrite test in the cli. 

---

public side of [pr512](https://github.com/canonical/multipass-private/pull/512)

Fixes #958

### CODE REVIEW

**Comment by sharder996** [comment]
Works on Linux. Need to verify on Windows/MacOS.

**Review by andrei-toterman — CHANGES_REQUESTED** [review]
I don't think this has much to do with the operating system itself, but with the terminal application that is used. The new Windows Terminal supports ANSI codes out of the box. And, if set up correctly, both Command Prompt and PowerShell support ANSI codes (at least in Windows 10 versions older than 2016). For example, the terminal integrated in VSCode enables ANSI support for them
image

You can look into [`GetStdHandle`](), [`GetConsoleMode`](https://learn.microsoft.com/en-us/windows/console/getconsolemode), [`SetConsoleMode`](), and `ENABLE_VIRTUAL_TERMINAL_PROCESSING` to try to enable ANSI codes on Windows, and fall back to the `std::setw` option if that fails. It could be something similar to this
```cpp
// in AnimatedSpinner ctor
auto terminal_handle = GetStdHandle(STD_OUTPUT_HANDLE);
unsigned long mode;
auto supports_ansi = GetConsoleMode(terminal_handle, &mode) &&
                     ((mode & ENABLE_VIRTUAL_TERMINAL_PROCESSING) ||
                     SetConsoleMode(terminal_handle, mode | ENABLE_VIRTUAL_TERMINAL_PROCESSING));

// in clear_line
if (supports_ansi) {
    // ansi stuff
} else {
    // fallback to std::setw
}
```

On Unix-like systems, checking the `TERM` environment variable is a common way of checking if the terminal supports ANSI codes.

I'm really not sure how to handle the situation in which `stdout` is not a terminal, i.e. when piping the output into another program. But I don't think that is in the scope of this PR, since right now the output is a mess and I don't see any people complaining about it.

**Comment by andrei-toterman** [comment]
I think abstracting this into a `bool terminal_supports_ansi()` method of `MP_PLATFORM` would be a good idea :)

**Comment by sharder996** [comment]
@andrei-toterman This is ready for review again!

Added a platform function for enabling ANSI codes on Windows which is going to fail when redirecting output to a file. But, that output was a already a mess in the first place and choked full of whitespace and newlines. 
The minimum Windows OS of Multipass is Windows 10 and I think expecting users will have installed an update from 2016 is pretty reasonable which is why I've chosen to ignore the return value from `SetConsoleMode()`. The alternative being to save the output and choose how to clear a line based on it. However, getting the value from the constructor of the client to the animated spinner would not be straightforward as the console mode only needs to set once per process, so setting it in the animated spinner would be a bit overkill.

**Review by andrei-toterman — APPROVED** [review]
Hey, @sharder996! Thanks for this!

bors merge

**Comment by andrei-toterman** [comment]
bors retry

**Pull request merged**
