### PR TITLE
[settings] Lock checked get and set

### LINKED ISSUE #1221: Make Settings thread-safe
To protect from different threads/processes colliding when reading/writing settings. Currently it is not very likely, but it is still something to protect against.

### PR DESCRIPTION
**Pull request by ricab**
To make settings thread safe. Fixes #1221.

### CODE REVIEW

**Comment by ricab** [comment]
Unit tests for this would require mocking `QSettings` (beyond the existing `MockSettings`), which was so far deferred. Let me know if you think that should get higher priority.

I tested manually with the following patch:

```patch
diff --git a/src/client/cli/cmd/set.cpp b/src/client/cli/cmd/set.cpp
index a894102..4c52323 100644
--- a/src/client/cli/cmd/set.cpp
+++ b/src/client/cli/cmd/set.cpp
@@ -25,6 +25,9 @@
 #include <multipass/rpc/multipass.grpc.pb.h>
 #include <multipass/settings.h>
 
+#include <thread> // FIXME testing
+#include <iostream> // FIXME testing
+
 namespace mp = multipass;
 namespace cmd = multipass::cmd;
 
@@ -36,10 +39,34 @@ bool allow_only_stopped_instances(const QString& key, const QString& val) // tem
            val != mp::Settings::instance().get(key); /* if we are switching between qemu and libvirt drivers (on linux),
                                                         we can only have stopped instances */
 }
+
+void run_test_threads() // FIXME testing
+{
+    std::vector<std::thread> threads{};
+
+    for(int i = 0; i < 1000; ++i)
+    {
+        threads.emplace_back([]() {
+            auto x = mp::Settings::instance().get("client.primary-name");
+            std::cout << x.toStdString() << "\n";
+        });
+        threads.emplace_back([i]() {
+            auto val = (i % 2) ? "foo" : "bar";
+            std::cout << "setting " << val << "\n";
+           mp::Settings::instance().set("client.primary-name", val);
+        });
+    }
+
+    std::cout << "joining\n";
+    for(auto& t : threads)
+        t.join();
+
+}
 } // namespace
 
 mp::ReturnCode cmd::Set::run(mp::ArgParser* parser)
 {
+    run_test_threads(); // FIXME testing
     auto parse_code = parse_args(parser);
     auto ret = parser->returnCodeFrom(parse_code);
     if (parse_code == ParseCode::Ok)
```

**Comment by ricab** [comment]
Of course, well spotted.

**Comment by ricab** [comment]
Done @townsend2010.

**Comment by townsend2010** [comment]
@ricab, great, thanks!

bors r+

**Comment by townsend2010** [comment]
Transient build issue it seems.  Try again...

bors r+

**Comment by legns** [comment]
How my second user...s8

angel labelle

**Pull request merged**
