### PR TITLE
Show in-app notification if an update is available

### PR DESCRIPTION
**Pull request by andrei-toterman**
This PR adds a notification if there is a Multipass update available.
There is also a refactoring for the update entry in the settings page.

### CODE REVIEW

**Review by sharder996 — CHANGES_REQUESTED** [review]
Tested and I see the update notification. However, it only shows up on launching the GUI. If I leave the GUI running long enough for `DefaultUpdatePrompt::is_time_to_show()` to return true again, I don't get another notification telling me about a newer version.

**Comment by sharder996** [comment]
As a follow-up, I'm not sure which is the preferred behaviour. Showing an update notification once on launch, or as per the update prompt timer. Multipass doesn't update that often so getting "live" update notifications might not be an issue.

**Comment by ricab** [comment]
Live notifications would be better, to quickly get to people who just suspend their laptop and keep the GUI running.

**Review by sharder996 — DISMISSED** [review]
Looks good!

Noticed that the update notification is not showing up in `start` and `restart` via the CLI even though we are piping the update info through the grpc reply. Addressing that is outside the scope of this PR, so I will create a bug report for it.

**Comment by andrei-toterman** [comment]
@sharder996 sorry to bother, but I just realized I was over-complicating things a little when extracting the update info from the rpc reply, so I pushed an update. Again, sorry for interrupting the merge :sweat_smile:

**Review by sharder996 — APPROVED** [review]

**Pull request merged**
