### PR TITLE
[lxd] Add support for suspending instances

### PR DESCRIPTION
**Pull request by townsend2010**

### CODE REVIEW

**Comment by townsend2010** [comment]
@Saviq,

> This doesn't survive reboots.

You mean if you "suspend", ie, freeze a VM, LXD doesn't remember the last state on host reboot?

> It really only does what it says on the tin - freezes the VM, doesn't store anything to disk.

That's a deficiency in LXD.  I plan to follow up with the LXD team, but this is the best LXD gives us for this.

**Comment by Saviq** [comment]
> > 
> 
> That's a deficiency in LXD. I plan to follow up with the LXD team, but this is the best LXD gives us for this.

Sure, and we should error out on `multipass suspend` until such a time that it actually works with LXD.

**Comment by townsend2010** [comment]
> we should error out on multipass suspend until such a time that it actually works with LXD

Oh, ok, I thought partial support was better than erroring out, but I'm fine with that.  I'll fix up this PR to strip out the suspend logic and throw the error instead.

**Comment by townsend2010** [comment]
This is replaced by #1604.

**Pull request closed without merging**
