### PR TITLE
[lxd] Wait on state operations to complete

### LINKED ISSUE #1785: [lxd] Starting instance is returning a "shutdown while starting" failure when that is not really happening
We are not waiting on the state change operation to complete before moving on, so we are being too quick on determining that the stated is `STOPPED` before LXD has had a chance to really start the VM.

We should wait on all state change operations to complete before moving on.

### PR DESCRIPTION
**Pull request by townsend2010**
Fixes #1785

### CODE REVIEW

**Comment by Saviq** [comment]
There seems to be more happening here… `focal` instances seem to reboot after first boot, so Multipass bails out, because the instance goes on→off→on…

**Comment by townsend2010** [comment]
> There seems to be more happening here… focal instances seem to reboot after first boot, so Multipass bails out, because the instance goes on→off→on…

I have not observed that behavior, but that is something for LXD to investigate.  I think we are doing what we are supposed to in this case.  The instance did indeed shutdown while starting.

**Comment by Saviq** [comment]
Yup.

bors r+

**Comment by Saviq** [comment]
Changes incoming…

bors r-

**Comment by townsend2010** [comment]
Ok, I fixed the looooong unit tests and added a best for a bit better coverage.

**Comment by Saviq** [comment]
Having launched two instances, I tried to `multipass delete -p --all` them, and Multipass got stuck:
```json
paź 15 12:55:47 michal-laptop multipassd[1500306]: Requesting LXD: GET unix://multipass/var/snap/lxd/common/lxd/unix.socket@1.0/operations/25e5c853-e6be-4b90-952e-49a417f325a8/wait?project=multipass
paź 15 12:55:47 michal-laptop multipassd[1500306]: Sending data: {}
paź 15 12:55:53 michal-laptop multipassd[1500306]: Got reply: {
                                                        "error": "",
                                                        "error_code": 0,
                                                        "metadata": {
                                                            "class": "task",
                                                            "created_at": "2020-10-15T12:55:47.547549237+02:00",
                                                            "description": "Stopping container",
                                                            "err": "",
                                                            "id": "25e5c853-e6be-4b90-952e-49a417f325a8",
                                                            "location": "none",
                                                            "may_cancel": false,
                                                            "metadata": null,
                                                            "resources": {
                                                                "containers": [
                                                                    "/1.0/containers/super-razorfish"
                                                                ]
                                                            },
                                                            "status": "Success",
                                                            "status_code": 200,
                                                            "updated_at": "2020-10-15T12:55:47.547549237+02:00"
                                                        },
                                                        "operation": "",
                                                        "status": "Success",
                                                        "status_code": 200,
                                                        "type": "sync"
                                                    }
```

```gdb
#0  0x00007f2605fd49f3 in pthread_cond_wait@@GLIBC_2.3.2 () from target:/lib/x86_64-linux-gnu/libpthread.so.0
No symbol table info available.
#1  0x00007f26047c88bc in std::condition_variable::wait(std::unique_lock<std::mutex>&) ()
   from target:/usr/lib/x86_64-linux-gnu/libstdc++.so.6
No symbol table info available.
#2  0x000055f3a463fab3 in std::condition_variable::wait<multipass::LXDVirtualMachine::stop()::<lambda()> > (__p=..., __lock=..., 
    this=0x55f3a5536480) at /usr/include/c++/7/condition_variable:99
No locals.
#3  multipass::LXDVirtualMachine::stop (this=0x55f3a5536450)
    at /root/parts/multipass/src/src/platform/backends/lxd/lxd_virtual_machine.cpp:244
        lock = {_M_device = 0x55f3a55364b0, _M_owns = true}
        present_state = <optimized out>
#4  0x000055f3a45beb4d in multipass::Daemon::delet (this=0x7ffdb3d92e70, request=0x7f25e8015920, server=<optimized out>, 
    status_promise=0x7f25da512700) at /root/parts/multipass/src/src/daemon/daemon.cpp:1659
        instance = @0x55f3a4f37f28: {<std::__shared_ptr<multipass::VirtualMachine, (__gnu_cxx::_Lock_policy)2>> = {<std::__shared_ptr_access<multipass::VirtualMachine, (__gnu_cxx::_Lock_policy)2, false, false>> = {<No data fields>}, _M_ptr = 0x55f3a5536450, 
            _M_refcount = {_M_pi = 0x55f3a553af60}}, <No data fields>}
        name = <optimized out>
        __for_range = @0x7ffdb3d925d0: {<std::_Vector_base<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >> = {
            _M_impl = {<std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >> = {<__gnu_cxx::new_allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >> = {<No data fields>}, <No data fields>}, _M_start = 0x55f3a55d8680, _M_finish = 0x55f3a55d86c0, _M_end_of_storage = 0x55f3a55d86c0}}, <No data fields>}
        __for_begin = <optimized out>
        __for_end = <optimized out>
        purge = true
        logger = {<multipass::logging::Logger> = {
            _vptr.Logger = 0x55f3a4d44238 <vtable for multipass::logging::ClientLogger<multipass::DeleteReply>+16>}, 
          logging_level = multipass::logging::Level::error, server = 0x7f25da512810, mpx_logger = @0x55f3a4ef5fe0}
        operational_instances_to_delete = <optimized out>
        trashed_instances_to_delete = <optimized out>
        status = <optimized out>
...
```

More gdb output here: [gdb.txt](https://github.com/canonical/multipass/files/5384346/gdb.txt)

**Comment by townsend2010** [comment]
@Saviq,

> Having launched two instances, I tried to `multipass delete -p --all` them, and Multipass got stuck:

Yep, looks you were struck by #1777.  That is not related to this PR.

**Pull request merged**
