### PR TITLE
[osx] fix old-style vmnet arguments

### PR DESCRIPTION
**Pull request by Saviq**

### CODE REVIEW

**Review by townsend2010 — APPROVED** [review]
Confirmed this does fix the issue.  The only thing I'm not a fan of is that this macOS specific code resides in the general process spec, but that's nothing to block on.

bors merge

**Comment by townsend2010** [comment]
Please try again...

bors retry

**Comment by Saviq** [comment]
bors retry

**Comment by townsend2010** [comment]
bors retry

**Pull request merged**
