### PR TITLE
[cli][launch] add bash completions for mount option

### PR DESCRIPTION
**Pull request by andrei-toterman**
Added bash completions for the `launch --mount` option.

### CODE REVIEW

**Review by luis4a0 — APPROVED** [review]
Thanks @andrei-toterman, looks good to me!

**Comment by andrei-toterman** [comment]
bors retry

**Comment by townsend2010** [comment]
bors is falling over with the "Publish-Snap" failure.  Let's get in the PR that fixes this first.

bors cancel

**Comment by townsend2010** [comment]
bors retry

**Comment by townsend2010** [comment]
bors r=lusi4a0

**Comment by townsend2010** [comment]
bors retry

**Comment by townsend2010** [comment]
Bah, it's just not meant to be....merging manually.

**Pull request merged**
