### PR TITLE
Introduce bug template

### PR DESCRIPTION
**Pull request by Saviq**
---

The result of this is:

https://github.com/Saviq/multipass/issues/new/choose

### CODE REVIEW

**Comment by townsend2010** [comment]
By the way, I noticed this by going to https://github.com/lxc/lxd/blob/master/.github/ISSUE_TEMPLATE.md and saw the message at the top.

**Comment by townsend2010** [comment]
Many bug reports we have been getting certainly are lacking the host OS, version, and logs.  And as we do more releases, the version of Multipass the user is running will become much more relevant.  I agree, bug templates that ask for quite a bit of detail are annoying at best and at worst will put of the user and they won't report anything.

I'm +1 as long as we keep it simple like this proposes.

**Comment by luis4a0** [comment]
@ricab : the template specify the steps to get the necessary information, I don't see a big harm asking for this info. We can at least say that something (like pasting the logs) is optional. I agree with @townsend2010 in that we _need_ these data.

**Comment by Saviq** [comment]
@townsend2010 I just used GitHub UI to create this… So their own UI generates an old template…

@ricab we can certainly reduce it if you feel it too heavy?

What I'd love in the long run is a `multipass report-bug` that will actually collect all of that data for the user. This is a first step in that direction, really.

**Comment by townsend2010** [comment]
> I just used GitHub UI to create this… So their own UI generates an old template…

lol, ok then...

**Comment by ricab** [comment]
@luis4a0, @townsend2010 I understand your points, thanks.

@Saviq nothing specific. Automating sounds interesting, even if we'd need to be careful with privacy stuff.

**Comment by Saviq** [comment]
I added a feature request template and a couple contact links, the result can be seen here:

https://github.com/Saviq/multipass/issues/new/choose

**Comment by Saviq** [comment]
bors r=townsend2010

**Pull request merged**
