### PR TITLE
ci: rework job-queues for new format

### PR DESCRIPTION
**Pull request by Saviq**
With the new Mini, we need more context than just `vmware-fusion` in the
job queue. For now Windows is left alone.

### CODE REVIEW

**Comment by Saviq** [comment]
bors try

**Comment by Saviq** [comment]
bors try

**Comment by Saviq** [comment]
bors try

**Comment by Saviq** [comment]
bors try

**Comment by Saviq** [comment]
OK now things should be sane. Right?

bors try

**Comment by Saviq** [comment]
bors try

**Comment by Saviq** [comment]
> Build failed:
> 
>     * [Windows](https://github.com/canonical/multipass/runs/7894400902)

Not funny.

**Comment by Saviq** [comment]
One more time.

bors try

**Comment by Saviq** [comment]
bors try

**Comment by Saviq** [comment]
> Build failed:

After some infrastructure issues, this is positive:

https://github.com/canonical/multipass/runs/7919655677

This moves all CI onto the new machine, once it lands we can rework the old one to only serve a single CI job plus the builders (or move the builders to the new one).

**Review by townsend2010 — APPROVED** [review]
Good stuff, thanks for this!

bors merge

**Comment by townsend2010** [comment]
The Mac action runners got stuck...

bors retry

**Pull request merged**
