### PR TITLE
[sshfs_mount] Add no compression and cache_timeout options

### LINKED ISSUE #1502: Disable sshfs file caching when mounting a folder.
I would like to easily be able to disable sshfs file caching when mounting a folder. 
Reason being that changes to files often take between 10 to 20 seconds to register for the vm.

Currently I've set up a script that creates a nfs folder mount from the vm to the host machine but this is kind of cumbersome and requires me to re-run the script when I switch network.

Maybe this can be fixed by adding the ability to add extra options to the 'multipass mount' command.

### PR DESCRIPTION
**Pull request by townsend2010**
Fixes #1502

### CODE REVIEW

**Comment by townsend2010** [comment]
@jasonmccallister,

Thanks for the feedback.   I did some `iozone` benchmarking and as a team, we've done some general observational testing.  It looks mostly well, but I'm being a little cautious with this as I don't want it to go in and all of a sudden we get a bunch of feedback saying, "OMG, my mounts are soooooo slow now!" :wink:  We'll discuss next week and make a final decision.

**Comment by brandonkelly** [comment]
Been testing this for the past day and it’s sooo much better :)

**Comment by Saviq** [comment]
I've now run a handful of scenarios to compare the performance and I've not seen any degradation, so let's get this in!

bors merge

**Comment by brandonkelly** [comment]
Awesome to see this make it into 1.4.0! Will that tag be getting a proper GH release? Until then, https://github.com/canonical/multipass/releases still shows 1.3.0 as the latest release.

**Comment by Saviq** [comment]
> Awesome to see this make it into 1.4.0! Will that tag be getting a proper GH release? Until then, https://github.com/canonical/multipass/releases still shows 1.3.0 as the latest release.

Yes, we're just going through the release process, should be able to release on Monday :)

**Pull request merged**
