### PR TITLE
[snapcraft] move from URLs to streams

### PR DESCRIPTION
**Pull request by Saviq**

### CODE REVIEW

**Comment by sergiusens** [comment]
I get this when trying the PR on _le_ mac:
```
launch failed: failed to download from 'https://cloud-images.ubuntu.com/daily/server/buildd/releases/focal/release-20200825/unpacked/focal-server-cloudimg-amd64-disk-vmlinuz-generic': Error transferring https://cloud-images.ubuntu.com/daily/server/buildd/releases/focal/release-20200825/unpacked/focal-server-cloudimg-amd64-disk-vmlinuz-generic - server replied: Not Found
```

**Comment by Saviq** [comment]
> I get this when trying the PR on _le_ mac:

Thanks @sergiusens, indeed those are missing, I just saw the `unpacked` folder and didn't look inside… Reported up to @davidkrauser.

BTW, would you expect a `snapcraft:core16` alias? There's only `core{,18,20}` at the moment.

**Comment by sergiusens** [comment]
Michał Sawicz writes:

>> I get this when trying the PR on _le_ mac:
> BTW, would you expect a `snapcraft:core16` alias? There's only `core{,18,20}` at the moment.

No need for core16, I don't know of any plans to bring this up to
production status:

```
name:      core16
summary:   core16 runtime environment
publisher: Canonical✓
store-url: https://snapcraft.io/core16
license:   unset
description: |
  The core16 runtime environment
type:    base
snap-id: lVwne2LSLAKRqY5zZV7Q3is2kJYfZhCS
channels:
  latest/stable:    –                                
  latest/candidate: –                                
  latest/beta:      16-20190110 2019-01-10 (46) 74MB -
  latest/edge:      16-20190110 2019-01-10 (46) 74MB -
```

**Comment by townsend2010** [comment]
This is done now, so closing this PR.

**Pull request closed without merging**
