### PR TITLE
[rpc] Convert RPC to use bi-directional streaming

### PR DESCRIPTION
**Pull request by townsend2010**

### CODE REVIEW

**Comment by townsend2010** [comment]
Hey @andrei-toterman,

I've now updated this.  Could you please give it another review pass?  Thanks!

**Comment by andrei-toterman** [comment]
Hey, @townsend2010! Code looks good, I tested it locally and everything seems to work just like before, as expected. I see that there are some conflicts with the private side though. Will this need a separate private PR as well?

**Comment by townsend2010** [comment]
Oh, and of course `bors` will fail because of the conflict, but it will be good to get it to run up to that point and then we can merge manually.

**Review by andrei-toterman — APPROVED** [review]
Alright, LGTM!

bors merge

**Pull request merged**
