### PR TITLE
Support snapcraft core22

### PR DESCRIPTION
**Pull request by townsend2010**

### CODE REVIEW

**Comment by luis4a0** [comment]
Thanks @townsend2010! Everything looks good. But there is a minor detail. We have a [black list of images on which bridging does not work](https://github.com/canonical/multipass/blob/9c51de654ea4ff4ca668a3b9852f5e2f89821130/src/daemon/daemon.cpp#L91). Please confirm we don't want to remove `xenial` from there (I htink not because it's still in `list --show-unsupported`).

**Comment by townsend2010** [comment]
@luis4a0,

You mean remove https://github.com/canonical/multipass/blob/9c51de654ea4ff4ca668a3b9852f5e2f89821130/src/daemon/daemon.cpp#L95 since we no longer support `snapcraft:core`?

**Comment by luis4a0** [comment]
Ok, let's remove `snapcraft:core` in another PR.

bors r+

**Comment by townsend2010** [comment]
bors retry

**Comment by townsend2010** [comment]
Hrm, try it again...

bors retry

**Comment by Saviq** [comment]
bors retry

**Comment by townsend2010** [comment]
One more time...

bors retry

**Pull request merged**
