### PR TITLE
Implements #1461

### PR DESCRIPTION
**Pull request by ianbtr**
Implements #1461.

This appears to work when using [this file](https://raw.githubusercontent.com/ianbtr/multipass/test_cloudinit_downloads/cloud_init_files/test.yml), like so:

`multipass launch --cloud-init https://raw.githubusercontent.com/ianbtr/multipass/test_cloudinit_downloads/cloud_init_files/test.yml`

Presently I'm unsure of how to add an appropriate test, is there a facility that mocks the URLDownloader?

### CODE REVIEW

**Comment by Saviq** [comment]
Hi @ianbtr thanks for this!

[tests/test_image_vault.cpp](https://github.com/canonical/multipass/blob/master/tests/test_image_vault.cpp#L90) has a handful of different mocked downloaders. The problem is that there currently isn't a way to pass it down from the test to the `cmd::Launch::parse_args()` method.

Looking at it it may be the right thing to pass the `mp::ClientConfig` instance to `cmd::Launch::run`, you would have to move parts of `::parse_args` (like actually reading the file in and downloading the file) into `::run`. You could then add a `URLDownloader` member to `mp::ClientConfig` and use it in `::run` - the test can then set a mock one in `send_command` and you will be able to check how it's used.

For a bigger contribution like that, I'll need to ask you to sign [the CLA](https://ubuntu.com/legal/contributors) please, if you have not done it yet :)

**Comment by Saviq** [comment]
Hi @ianbtr are you able to finish this up with tests?

**Comment by ianbtr** [comment]
Unfortunately, I will not be able to finish writing tests.

**Comment by townsend2010** [comment]
We incorporated this in #2593 and is now merged!  Thanks and I'll close this PR!

**Pull request closed without merging**
