### PR TITLE
submodules/grpc: Update grpc submodule branch

### PR DESCRIPTION
**Pull request by townsend2010**

### CODE REVIEW

**Comment by ricab** [comment]
Hey @townsend2010 , just to let you know I tried this to see if it would help fix the debug-build failure in disco and I got earlier errors there (in boringssl). Those appeared in both debug and release. 

In both cases the problems are caused by warnings that are promoted to errors (I guess the compiler is more thorough). I wonder if we should disable that in 3rd party stuff, since it is out of our reach...

**Comment by townsend2010** [comment]
Even though this was originally my PR, the work needed to get the coverage building was done by @ricab, so I'll review this :grin:

**Comment by ricab** [comment]
@townsend2010 hey, just a heads-up that I had to force-push to fix a wrong comment.

**Comment by ricab** [comment]
OK, thanks @townsend2010. 

bors r+

**Pull request merged**
