### PR TITLE
[backend/qemu] Increase shutdown/suspend timeout to 5 minutes

### LINKED ISSUE #2933: [qemu] Allow more than 30 seconds to shutdown/suspend an instance
Currently, only 30 seconds are allowed to shutdown or suspend an instance before it kills `qemu`.  We should allow more time as the instance or host machine is busy.

### PR DESCRIPTION
**Pull request by townsend2010**
Fixes #2933

### CODE REVIEW

**Comment by sharder996** [comment]
We're doing some similar with LXD [here](https://github.com/canonical/multipass/blob/0c58deb74c38bfc364311cae38b4b14b3646fec9/src/platform/backends/lxd/lxd_virtual_machine.cpp#L189) that has been left with a comment that we should probably be passing in the timeout from the daemon (or at least consulting it). The engineering required to do that might not be feasible at this time, but maybe we should create a ticket so it doesn't get buried.

**Review by sharder996 — APPROVED** [review]
Ok, LGTM! Just didn't want to lose track of the other issue.

bors merge

**Comment by sharder996** [comment]
bors retry

**Comment by townsend2010** [comment]
Last time...

bors retry

**Pull request merged**
