### PR TITLE
[daemon] Move starting instances back to main thread

### LINKED ISSUE #2646: [regression] Errors in starting instances are not detected and start detection will continue
For example, allocating too much memory to an instance using the `qemu` driver causes `qemu` to error out, but the daemon does not detect this and will continue to keep trying to detect when the instance is ready.

### PR DESCRIPTION
**Pull request by townsend2010**
Fixes #2646

### CODE REVIEW

**Comment by luis4a0** [comment]
Hi @andrei-toterman, thanks for the thorough testing! You're right on libvirt this seems buggy, but this behavior was already present in 1.9.2. So this is not a regression, but a preexisting issue with libvirt. Thanks for going deep into this!

**Comment by luis4a0** [comment]
@andrei-toterman @townsend2010, do you agree we merge this now and later investigate the issue with libvirt?

**Comment by andrei-toterman** [comment]
@luis4a0 I agree. This still fixes the majority of cases

**Comment by luis4a0** [comment]
Great @andrei-toterman, so we have two votes for merging. Let's go!

bors r+

**Comment by luis4a0** [comment]
bors retry

**Comment by luis4a0** [comment]
Something weird is happening here... bors is consistently timing out.

**Comment by townsend2010** [comment]
One more time...

bors retry

**Pull request merged**
