### PR TITLE
Complete bridge options in `launch` command

### PR DESCRIPTION
**Pull request by luis4a0**
This PR adds bash completions for the options `--bridged` and `--network bridged` of the `launch` command.

### CODE REVIEW

**Review by townsend2010 — APPROVED** [review]
Yup!

bors merge

**Comment by townsend2010** [comment]
bors retry

**Comment by ricab** [comment]
bors r=townsend2010

**Comment by ricab** [comment]
bahh
bors retry

**Comment by ricab** [comment]
:sob:

bors retry

**Comment by townsend2010** [comment]
One more time:

bors retry

**Comment by Saviq** [comment]
bors retry

**Pull request merged**
