### PR TITLE
[cmake] Drop needless grpc compilation option

### PR DESCRIPTION
**Pull request by ricab**
Did its job, no longer needed :)

### CODE REVIEW

**Review by luis4a0 — APPROVED** [review]
Hey @ricab, thanks for this. Looks good to me and works.

**Comment by luis4a0** [comment]
@Saviq @ricab Do you know what's the above message? Am I not supposed to be the reviewer?

**Comment by ricab** [comment]
I was just puzzling about that myself...

**Comment by luis4a0** [comment]
Worked. Thanks @Saviq!

**Comment by Saviq** [comment]
clang segfault.

bors retry

**Comment by Saviq** [comment]
bors retry

**Comment by ricab** [comment]
Hmm Github/Codecov issue now: `{'detail': ErrorDetail(string='Unable to locate build via Github Actions API. Please upload with the Codecov repository upload token to resolve issue.', code='not_found')}`.

bors retry

**Comment by ricab** [comment]
Now [AppleClang aborted](https://github.com/canonical/multipass-private/runs/4880756047?check_suite_focus=true#step:22:9432). Why does bors say it was Windows that failed?

bors retry

**Comment by luis4a0** [comment]
:facepalm:

bors retry

**Comment by ricab** [comment]
Hmm, something seems to be going amiss with authentication: https://github.com/canonical/multipass/runs/4881931319?check_suite_focus=true#step:4:1613

**Pull request merged**
